// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Factors;
using System.Collections.Generic;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2301.301 at 5:57 PM on Wednesday, August 9, 2023.
	/// </remarks>
	public partial class DialogueDirector_Gibbs : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>Field backing the AllEvents property</summary>
		private int[] AllEvents_field;
		/// <summary>Field backing the AllRels property</summary>
		private int[] AllRels_field;
		/// <summary>Message from marginal of 'AllTraits'</summary>
		public DistributionRefArray<Discrete,int> AllTraits_marginal_B;
		public Discrete AllTraits_marginal_B_reduced;
		/// <summary>Message to marginal of 'AllTraits'</summary>
		public GibbsMarginal<DistributionRefArray<Discrete,int>,int[]> AllTraits_marginal_F;
		/// <summary>True if Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors has executed. Set this to false to force re-execution of Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors</summary>
		public bool Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone;
		/// <summary>True if Changed_DialogueCPTPrior has executed. Set this to false to force re-execution of Changed_DialogueCPTPrior</summary>
		public bool Changed_DialogueCPTPrior_isDone;
		/// <summary>True if Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors has executed. Set this to false to force re-execution of Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors</summary>
		public bool Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isDone;
		/// <summary>True if Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors has performed initialisation. Set this to false to force re-execution of Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors</summary>
		public bool Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised;
		/// <summary>True if Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors</summary>
		public bool Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors</summary>
		public bool Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised;
		/// <summary>True if Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases</summary>
		public bool Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases</summary>
		public bool Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised;
		/// <summary>True if Changed_NumOfCases has executed. Set this to false to force re-execution of Changed_NumOfCases</summary>
		public bool Changed_NumOfCases_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		/// <summary>Message from marginal of 'DialogueChild'</summary>
		public DistributionRefArray<Discrete,int> DialogueChild_marginal_B;
		public Discrete DialogueChild_marginal_B_reduced;
		/// <summary>Message to marginal of 'DialogueChild'</summary>
		public GibbsMarginal<DistributionRefArray<Discrete,int>,int[]> DialogueChild_marginal_F;
		/// <summary>Message to marginal of 'DialogueChild_NCases__Traits'</summary>
		public GibbsMarginal<Discrete,int>[][] DialogueChild_NCases__Traits_marginal_F;
		/// <summary>Message from marginal of 'DialogueCPT'</summary>
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPT_marginal_B;
		/// <summary>Message to marginal of 'DialogueCPT'</summary>
		public GibbsMarginal<DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>,Vector[][][]> DialogueCPT_marginal_F;
		/// <summary>Messages from uses of 'DialogueCPT'</summary>
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>[] DialogueCPT_uses_B;
		/// <summary>Field backing the DialogueCPTPrior property</summary>
		private Dirichlet[][][] DialogueCPTPrior_field;
		/// <summary>Field backing the EventsPriors property</summary>
		private Dirichlet EventsPriors_field;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Field backing the NumOfCases property</summary>
		private int NumOfCases_field;
		/// <summary>Message to marginal of 'PossibleTraits'</summary>
		public GibbsMarginal<Dirichlet,Vector> PossibleTraits_marginal_F;
		/// <summary>Messages from uses of 'PossibleTraits'</summary>
		public Dirichlet[] PossibleTraits_uses_B;
		/// <summary>Field backing the RelStatusPriors property</summary>
		private Dirichlet RelStatusPriors_field;
		/// <summary>Field backing the TraitsPriors property</summary>
		private Dirichlet TraitsPriors_field;
		#endregion

		#region Properties
		/// <summary>The externally-specified value of 'AllEvents'</summary>
		public int[] AllEvents
		{
			get {
				return this.AllEvents_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.NumOfCases)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.NumOfCases)+" was expected for variable \'AllEvents\'");
				}
				this.AllEvents_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised = false;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'AllRels'</summary>
		public int[] AllRels
		{
			get {
				return this.AllRels_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.NumOfCases)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.NumOfCases)+" was expected for variable \'AllRels\'");
				}
				this.AllRels_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised = false;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'DialogueCPTPrior'</summary>
		public Dirichlet[][][] DialogueCPTPrior
		{
			get {
				return this.DialogueCPTPrior_field;
			}
			set {
				if ((value!=null)&&(value.Length!=215)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+215)+" was expected for variable \'DialogueCPTPrior\'");
				}
				this.DialogueCPTPrior_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised = false;
				this.Changed_DialogueCPTPrior_isDone = false;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isDone = false;
				this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'EventsPriors'</summary>
		public Dirichlet EventsPriors
		{
			get {
				return this.EventsPriors_field;
			}
			set {
				this.EventsPriors_field = value;
				this.numberOfIterationsDone = 0;
			}
		}

		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'NumOfCases'</summary>
		public int NumOfCases
		{
			get {
				return this.NumOfCases_field;
			}
			set {
				if (this.NumOfCases_field!=value) {
					this.NumOfCases_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_NumOfCases_isDone = false;
					this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isDone = false;
					this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised = false;
					this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised = false;
					this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
				}
			}
		}

		/// <summary>The externally-specified value of 'RelStatusPriors'</summary>
		public Dirichlet RelStatusPriors
		{
			get {
				return this.RelStatusPriors_field;
			}
			set {
				this.RelStatusPriors_field = value;
				this.numberOfIterationsDone = 0;
			}
		}

		/// <summary>The externally-specified value of 'TraitsPriors'</summary>
		public Dirichlet TraitsPriors
		{
			get {
				return this.TraitsPriors_field;
			}
			set {
				this.TraitsPriors_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised = false;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isDone = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of AllEvents and AllRels and DialogueCPTPrior and numberOfIterations and NumOfCases and TraitsPriors</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors(int numberOfIterations)
		{
			if (this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone) {
				return ;
			}
			Vector[] PossibleTraits_uses_F;
			// Create array for 'PossibleTraits_uses' Forwards messages.
			PossibleTraits_uses_F = new Vector[1];
			Discrete AllTraits_F_reduced;
			AllTraits_F_reduced = default(Discrete);
			if (this.NumOfCases>0) {
				AllTraits_F_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
			}
			DistributionRefArray<Discrete,int> AllTraits_F;
			// Create array for 'AllTraits' Forwards messages.
			AllTraits_F = new DistributionRefArray<Discrete,int>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				AllTraits_F[NCases] = AllTraits_F_reduced;
			}
			// Create array for replicates of 'AllTraits_NCases__selector_uses_B'
			Discrete[][] AllTraits_NCases__selector_uses_B = new Discrete[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_uses' Backwards messages.
				AllTraits_NCases__selector_uses_B[NCases] = new Discrete[2];
				AllTraits_NCases__selector_uses_B[NCases][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
				AllTraits_NCases__selector_uses_B[NCases][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
			}
			// Create array for replicates of 'AllTraits_NCases__selector_cases_uses_B'
			DistributionStructArray<Bernoulli,bool>[][] AllTraits_NCases__selector_cases_uses_B = new DistributionStructArray<Bernoulli,bool>[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases] = new DistributionStructArray<Bernoulli,bool>[6];
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases][0] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_uses_B[NCases][0][Traits] = Bernoulli.Uniform();
				}
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases][1] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_uses_B[NCases][1][Traits] = Bernoulli.Uniform();
				}
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases][4] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_uses_B[NCases][4][Traits] = Bernoulli.Uniform();
				}
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases][2] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_uses_B[NCases][2][Traits] = Bernoulli.Uniform();
				}
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases][3] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_uses_B[NCases][3][Traits] = Bernoulli.Uniform();
				}
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases][5] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_uses_B[NCases][5][Traits] = Bernoulli.Uniform();
				}
			}
			Discrete[][] DialogueChild_NCases__Traits_uses_B_reduced = new Discrete[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				DialogueChild_NCases__Traits_uses_B_reduced[NCases] = default(Discrete[]);
				// Create array for 'DialogueChild_NCases__Traits_uses' Backwards messages.
				DialogueChild_NCases__Traits_uses_B_reduced[NCases] = new Discrete[1];
				DialogueChild_NCases__Traits_uses_B_reduced[NCases][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(670));
			}
			DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPT_F;
			// Create array for 'DialogueCPT' Forwards messages.
			DialogueCPT_F = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(215);
			for(int Events = 0; Events<215; Events++) {
				// Create array for 'DialogueCPT' Forwards messages.
				DialogueCPT_F[Events] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(14);
			}
			for(int Traits = 0; Traits<14; Traits++) {
				for(int Events = 0; Events<215; Events++) {
					// Create array for 'DialogueCPT' Forwards messages.
					DialogueCPT_F[Events][Traits] = new DistributionRefArray<Dirichlet,Vector>(3);
					for(int Rel = 0; Rel<3; Rel++) {
						DialogueCPT_F[Events][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][Rel]);
						// Message to 'DialogueCPT' from Random factor
						DialogueCPT_F[Events][Traits][Rel] = ArrayHelper.SetTo<Dirichlet>(DialogueCPT_F[Events][Traits][Rel], this.DialogueCPTPrior[Events][Traits][Rel]);
					}
				}
			}
			DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>[] DialogueCPT_itemAllEvents_NCases__uses_B;
			// Create array for 'DialogueCPT_itemAllEvents_NCases__uses' Backwards messages.
			DialogueCPT_itemAllEvents_NCases__uses_B = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>[1];
			// Create array for 'DialogueCPT_itemAllEvents_NCases__uses' Backwards messages.
			DialogueCPT_itemAllEvents_NCases__uses_B[0] = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'DialogueCPT_itemAllEvents_NCases__uses' Backwards messages.
				DialogueCPT_itemAllEvents_NCases__uses_B[0][NCases] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					// Create array for 'DialogueCPT_itemAllEvents_NCases__uses' Backwards messages.
					DialogueCPT_itemAllEvents_NCases__uses_B[0][NCases][Traits] = new DistributionRefArray<Dirichlet,Vector>(3);
					for(int Rel = 0; Rel<3; Rel++) {
						DialogueCPT_itemAllEvents_NCases__uses_B[0][NCases][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[this.AllEvents[NCases]][Traits][Rel]);
					}
				}
			}
			int[][] AllTraits_uses_F;
			// Create array for 'AllTraits_uses' Forwards messages.
			AllTraits_uses_F = new int[1][];
			// Create array for 'AllTraits_uses' Forwards messages.
			AllTraits_uses_F[0] = new int[this.NumOfCases];
			// Create array for replicates of 'DialogueChild_NCases__Traits_B'
			int[][] DialogueChild_NCases__Traits_B = new int[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for replicates of 'DialogueChild_NCases__Traits_B'
				DialogueChild_NCases__Traits_B[NCases] = new int[14];
				for(int Traits = 0; Traits<14; Traits++) {
					DialogueChild_NCases__Traits_B[NCases][Traits] = default(int);
				}
			}
			// Create array for replicates of 'DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses_B'
			Dirichlet[][][] DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses_B = new Dirichlet[this.NumOfCases][][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for replicates of 'DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses_B'
				DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses_B[NCases] = new Dirichlet[14][];
				for(int Traits = 0; Traits<14; Traits++) {
					// Create array for 'DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses' Backwards messages.
					DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses_B[NCases][Traits] = new Dirichlet[1];
					DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses_B[NCases][Traits][0] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[this.AllEvents[NCases]][Traits][this.AllRels[NCases]]);
				}
			}
			// Create array for replicates of 'DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B'
			Dirichlet[][] DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B = new Dirichlet[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for replicates of 'DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B'
				DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B[NCases] = new Dirichlet[14];
				for(int Traits = 0; Traits<14; Traits++) {
					DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B[NCases][Traits] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[this.AllEvents[NCases]][Traits][this.AllRels[NCases]]);
				}
			}
			DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPT_itemAllEvents_NCases__B;
			// Create array for 'DialogueCPT_itemAllEvents_NCases_' Backwards messages.
			DialogueCPT_itemAllEvents_NCases__B = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'DialogueCPT_itemAllEvents_NCases_' Backwards messages.
				DialogueCPT_itemAllEvents_NCases__B[NCases] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					// Create array for 'DialogueCPT_itemAllEvents_NCases_' Backwards messages.
					DialogueCPT_itemAllEvents_NCases__B[NCases][Traits] = new DistributionRefArray<Dirichlet,Vector>(3);
					for(int Rel = 0; Rel<3; Rel++) {
						DialogueCPT_itemAllEvents_NCases__B[NCases][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[this.AllEvents[NCases]][Traits][Rel]);
					}
				}
			}
			Vector[][][][] DialogueCPT_uses_F;
			// Create array for 'DialogueCPT_uses' Forwards messages.
			DialogueCPT_uses_F = new Vector[1][][][];
			// Create array for 'DialogueCPT_uses' Forwards messages.
			DialogueCPT_uses_F[0] = new Vector[215][][];
			for(int Events = 0; Events<215; Events++) {
				// Create array for 'DialogueCPT_uses' Forwards messages.
				DialogueCPT_uses_F[0][Events] = new Vector[14][];
			}
			for(int Traits = 0; Traits<14; Traits++) {
				for(int Events = 0; Events<215; Events++) {
					// Create array for 'DialogueCPT_uses' Forwards messages.
					DialogueCPT_uses_F[0][Events][Traits] = new Vector[3];
				}
			}
			Vector[][][] DialogueCPT_itemAllEvents_NCases__F;
			// Create array for 'DialogueCPT_itemAllEvents_NCases_' Forwards messages.
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'DialogueCPT_itemAllEvents_NCases_' Forwards messages.
				for(int Traits = 0; Traits<14; Traits++) {
					// Create array for 'DialogueCPT_itemAllEvents_NCases_' Forwards messages.
				}
			}
			// Create array for replicates of 'DialogueChild_NCases__Traits_F'
			Discrete[][] DialogueChild_NCases__Traits_F = new Discrete[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for replicates of 'DialogueChild_NCases__Traits_F'
				DialogueChild_NCases__Traits_F[NCases] = new Discrete[14];
				for(int Traits = 0; Traits<14; Traits++) {
					DialogueChild_NCases__Traits_F[NCases][Traits] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(670));
				}
			}
			DistributionRefArray<Discrete,int> DialogueChild_B;
			// Create array for 'DialogueChild' Backwards messages.
			DialogueChild_B = new DistributionRefArray<Discrete,int>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				DialogueChild_B[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(670));
			}
			// Create array for replicates of 'DialogueChild_NCases__F'
			int[][] DialogueChild_NCases__F = new int[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'DialogueChild_NCases_' Forwards messages.
				DialogueChild_NCases__F[NCases] = new int[14];
			}
			// Create array for replicates of 'DialogueChild_NCases__Traits_uses_F'
			int[][][] DialogueChild_NCases__Traits_uses_F = new int[this.NumOfCases][][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for replicates of 'DialogueChild_NCases__Traits_uses_F'
				DialogueChild_NCases__Traits_uses_F[NCases] = new int[14][];
				for(int Traits = 0; Traits<14; Traits++) {
					// Create array for 'DialogueChild_NCases__Traits_uses' Forwards messages.
					DialogueChild_NCases__Traits_uses_F[NCases][Traits] = new int[1];
				}
			}
			// Create array for replicates of 'AllTraits_NCases__selector_cases_B'
			DistributionStructArray<Bernoulli,bool>[] AllTraits_NCases__selector_cases_B = new DistributionStructArray<Bernoulli,bool>[this.NumOfCases];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_cases' Backwards messages.
				AllTraits_NCases__selector_cases_B[NCases] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_B[NCases][Traits] = Bernoulli.Uniform();
				}
			}
			// Create array for replicates of 'AllTraits_NCases__selector_B'
			Discrete[] AllTraits_NCases__selector_B = new Discrete[this.NumOfCases];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				AllTraits_NCases__selector_B[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
			}
			DistributionRefArray<Discrete,int>[] AllTraits_uses_B;
			// Create array for 'AllTraits_uses' Backwards messages.
			AllTraits_uses_B = new DistributionRefArray<Discrete,int>[1];
			// Create array for 'AllTraits_uses' Backwards messages.
			AllTraits_uses_B[0] = new DistributionRefArray<Discrete,int>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				AllTraits_uses_B[0][NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
			}
			int[] AllTraits_B;
			// Create array for 'AllTraits' Backwards messages.
			AllTraits_B = new int[this.NumOfCases];
			DistributionRefArray<Dirichlet,Vector>[] PossibleTraits_rep_uses_B;
			// Create array for 'PossibleTraits_rep_uses' Backwards messages.
			PossibleTraits_rep_uses_B = new DistributionRefArray<Dirichlet,Vector>[1];
			// Create array for 'PossibleTraits_rep_uses' Backwards messages.
			PossibleTraits_rep_uses_B[0] = new DistributionRefArray<Dirichlet,Vector>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				PossibleTraits_rep_uses_B[0][NCases] = ArrayHelper.MakeUniform<Dirichlet>(this.TraitsPriors);
			}
			DistributionRefArray<Dirichlet,Vector> PossibleTraits_rep_B;
			// Create array for 'PossibleTraits_rep' Backwards messages.
			PossibleTraits_rep_B = new DistributionRefArray<Dirichlet,Vector>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				PossibleTraits_rep_B[NCases] = ArrayHelper.MakeUniform<Dirichlet>(this.TraitsPriors);
			}
			int[] DialogueChild_F;
			// Create array for 'DialogueChild' Forwards messages.
			DialogueChild_F = new int[this.NumOfCases];
			// Create array for replicates of 'AllTraits_NCases__selector_cases_F'
			bool[][] AllTraits_NCases__selector_cases_F = new bool[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_cases' Forwards messages.
				AllTraits_NCases__selector_cases_F[NCases] = new bool[14];
			}
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				// Message to 'PossibleTraits_marginal' from UsesEqualDef factor
				this.PossibleTraits_marginal_F = UsesEqualDefGibbsOp<Vector>.MarginalGibbs<Dirichlet>(this.PossibleTraits_uses_B, this.TraitsPriors, this.PossibleTraits_marginal_F);
				// Message to 'PossibleTraits_uses' from UsesEqualDef factor
				PossibleTraits_uses_F[0] = UsesEqualDefGibbsOp<Vector>.UsesGibbs<Dirichlet>(this.PossibleTraits_marginal_F, 0, PossibleTraits_uses_F[0]);
				if (this.NumOfCases>0) {
					// Message to 'AllTraits' from Discrete factor
					AllTraits_F_reduced = DiscreteFromDirichletOp.SampleAverageConditional(PossibleTraits_uses_F[0], AllTraits_F_reduced);
				}
				for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
					AllTraits_F[NCases] = AllTraits_F_reduced;
				}
				// Message to 'DialogueCPT_marginal' from UsesEqualDef factor
				this.DialogueCPT_marginal_F = UsesEqualDefGibbsOp<Vector[][][]>.MarginalGibbs<DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>>(this.DialogueCPT_uses_B, DialogueCPT_F, this.DialogueCPT_marginal_F);
				// Message to 'DialogueCPT_uses' from UsesEqualDef factor
				DialogueCPT_uses_F[0] = UsesEqualDefGibbsOp<Vector[][][]>.UsesGibbs<DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>>(this.DialogueCPT_marginal_F, 0, DialogueCPT_uses_F[0]);
				// Message to 'DialogueCPT_itemAllEvents_NCases_' from GetItems factor
				DialogueCPT_itemAllEvents_NCases__F = Collection.GetItems<Vector[][]>(DialogueCPT_uses_F[0], this.AllEvents);
				for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
					for(int Traits = 0; Traits<14; Traits++) {
						// Message to 'DialogueChild_NCases__Traits' from Discrete factor
						DialogueChild_NCases__Traits_F[NCases][Traits] = DiscreteFromDirichletOp.SampleAverageConditional(DialogueCPT_itemAllEvents_NCases__F[NCases][Traits][this.AllRels[NCases]], DialogueChild_NCases__Traits_F[NCases][Traits]);
						// Message to 'DialogueChild_NCases__Traits_marginal' from UsesEqualDef factor
						this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits] = UsesEqualDefGibbsOp<int>.MarginalGibbs<Discrete>(DialogueChild_NCases__Traits_uses_B_reduced[NCases], DialogueChild_NCases__Traits_F[NCases][Traits], this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits]);
						// Message to 'AllTraits_NCases__selector_cases_uses' from UsesEqualDef factor
						AllTraits_NCases__selector_cases_uses_B[NCases][2][Traits] = Bernoulli.FromLogOdds(UsesEqualDefGibbsOp<int>.GibbsEvidence<Discrete>(DialogueChild_NCases__Traits_uses_B_reduced[NCases], DialogueChild_NCases__Traits_F[NCases][Traits], this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits]));
						// Message to 'DialogueChild_NCases__Traits' from UsesEqualDef factor
						DialogueChild_NCases__Traits_B[NCases][Traits] = UsesEqualDefGibbsOp<int>.DefGibbs<Discrete>(this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits], DialogueChild_NCases__Traits_B[NCases][Traits]);
						// Message to 'DialogueChild_NCases__Traits_uses' from UsesEqualDef factor
						DialogueChild_NCases__Traits_uses_F[NCases][Traits][0] = UsesEqualDefGibbsOp<int>.UsesGibbs<Discrete>(this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits], 0, DialogueChild_NCases__Traits_uses_F[NCases][Traits][0]);
						// Message to 'DialogueChild_NCases_' from Copy factor
						DialogueChild_NCases__F[NCases][Traits] = Clone.Copy<int>(DialogueChild_NCases__Traits_uses_F[NCases][Traits][0]);
						// Message to 'AllTraits_NCases__selector_cases_uses' from Discrete factor
						AllTraits_NCases__selector_cases_uses_B[NCases][3][Traits] = Bernoulli.FromLogOdds(DiscreteFromDirichletOp.LogEvidenceRatio(DialogueChild_NCases__Traits_B[NCases][Traits], DialogueCPT_itemAllEvents_NCases__F[NCases][Traits][this.AllRels[NCases]]));
					}
					for(int Traits = 0; Traits<14; Traits++) {
						// Message to 'AllTraits_NCases__selector_cases_uses' from Exit factor
						AllTraits_NCases__selector_cases_uses_B[NCases][5][Traits] = GateExitOp<int>.CasesAverageConditional<Discrete>(DialogueChild_B[NCases], DialogueChild_NCases__F[NCases], Traits);
					}
					// Message to 'AllTraits_NCases__selector_cases' from ReplicateWithMarginal factor
					AllTraits_NCases__selector_cases_B[NCases] = ReplicateGibbsOp<bool[]>.DefGibbs<DistributionStructArray<Bernoulli,bool>>(AllTraits_NCases__selector_cases_uses_B[NCases], AllTraits_NCases__selector_cases_B[NCases]);
					// Message to 'AllTraits_NCases__selector_uses' from CasesInt factor
					AllTraits_NCases__selector_uses_B[NCases][0] = IntCasesOp.IAverageConditional(AllTraits_NCases__selector_cases_B[NCases], AllTraits_NCases__selector_uses_B[NCases][0]);
					// Message to 'AllTraits_NCases__selector' from ReplicateWithMarginal factor
					AllTraits_NCases__selector_B[NCases] = ReplicateGibbsOp<int>.DefGibbs<Discrete>(AllTraits_NCases__selector_uses_B[NCases], AllTraits_NCases__selector_B[NCases]);
					// Message to 'AllTraits_uses' from Copy factor
					AllTraits_uses_B[0][NCases] = ArrayHelper.SetTo<Discrete>(AllTraits_uses_B[0][NCases], AllTraits_NCases__selector_B[NCases]);
				}
				// Message to 'AllTraits_marginal' from UsesEqualDef factor
				this.AllTraits_marginal_F = UsesEqualDefGibbsOp<int[]>.MarginalGibbs<DistributionRefArray<Discrete,int>>(AllTraits_uses_B, AllTraits_F, this.AllTraits_marginal_F);
				// Message to 'AllTraits' from UsesEqualDef factor
				AllTraits_B = UsesEqualDefGibbsOp<int[]>.DefGibbs<DistributionRefArray<Discrete,int>>(this.AllTraits_marginal_F, AllTraits_B);
				for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
					// Message to 'PossibleTraits_rep_uses' from Discrete factor
					PossibleTraits_rep_uses_B[0][NCases] = DiscreteFromDirichletOp.ProbsAverageConditional(AllTraits_B[NCases], PossibleTraits_rep_uses_B[0][NCases]);
				}
				// Message to 'PossibleTraits_rep' from ReplicateWithMarginal factor
				PossibleTraits_rep_B = ReplicateGibbsOp<Vector[]>.DefGibbs<DistributionRefArray<Dirichlet,Vector>>(PossibleTraits_rep_uses_B, PossibleTraits_rep_B);
				// Message to 'PossibleTraits_uses' from Replicate factor
				this.PossibleTraits_uses_B[0] = ReplicateOp_NoDivide.DefAverageConditional<Dirichlet>(PossibleTraits_rep_B, this.PossibleTraits_uses_B[0]);
				// Message to 'AllTraits_uses' from UsesEqualDef factor
				AllTraits_uses_F[0] = UsesEqualDefGibbsOp<int[]>.UsesGibbs<DistributionRefArray<Discrete,int>>(this.AllTraits_marginal_F, 0, AllTraits_uses_F[0]);
				for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
					for(int Traits = 0; Traits<14; Traits++) {
						// Message to 'DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses' from Discrete factor
						DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses_B[NCases][Traits][0] = DiscreteFromDirichletOp.ProbsAverageConditional(DialogueChild_NCases__Traits_B[NCases][Traits], DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses_B[NCases][Traits][0]);
						// Message to 'DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases__' from ReplicateWithMarginal factor
						DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B[NCases][Traits] = ReplicateGibbsOp<Vector>.DefGibbs<Dirichlet>(DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___uses_B[NCases][Traits], DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B[NCases][Traits]);
						// Message to 'DialogueCPT_itemAllEvents_NCases__uses' from EnterOne factor
						DialogueCPT_itemAllEvents_NCases__uses_B[0][NCases][Traits][this.AllRels[NCases]] = GateEnterOneOp<Vector>.ValueAverageConditional<Dirichlet>(DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B[NCases][Traits], AllTraits_uses_F[0][NCases], Traits, DialogueCPT_itemAllEvents_NCases__uses_B[0][NCases][Traits][this.AllRels[NCases]]);
					}
				}
				// Message to 'DialogueCPT_itemAllEvents_NCases_' from ReplicateWithMarginal factor
				DialogueCPT_itemAllEvents_NCases__B = ReplicateGibbsOp<Vector[][][]>.DefGibbs<DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>>(DialogueCPT_itemAllEvents_NCases__uses_B, DialogueCPT_itemAllEvents_NCases__B);
				// Message to 'DialogueCPT_uses' from GetItems factor
				this.DialogueCPT_uses_B[0] = GetItemsOp<Vector[][]>.ArrayAverageConditional<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>>(DialogueCPT_itemAllEvents_NCases__B, this.AllEvents, this.DialogueCPT_uses_B[0]);
				for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
					// Message to 'AllTraits_NCases__selector_cases' from CasesInt factor
					AllTraits_NCases__selector_cases_F[NCases] = Gate.CasesInt(AllTraits_uses_F[0][NCases], 14);
					// Message to 'DialogueChild' from Exit factor
					DialogueChild_F[NCases] = Gate.Exit<int>(AllTraits_NCases__selector_cases_F[NCases], DialogueChild_NCases__F[NCases]);
				}
				// Message to 'DialogueChild_marginal' from ReplicateWithMarginal factor
				this.DialogueChild_marginal_F = ReplicateGibbsOp<int[]>.MarginalGibbs<DistributionRefArray<Discrete,int>,int[]>(DialogueChild_F, this.DialogueChild_marginal_F);
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of DialogueCPTPrior</summary>
		private void Changed_DialogueCPTPrior()
		{
			if (this.Changed_DialogueCPTPrior_isDone) {
				return ;
			}
			for(int Traits = 0; Traits<14; Traits++) {
				for(int Events = 0; Events<215; Events++) {
					for(int Rel = 0; Rel<3; Rel++) {
						this.DialogueCPT_marginal_B[Events][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][Rel]);
					}
				}
			}
			this.Changed_DialogueCPTPrior_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of DialogueCPTPrior and numberOfIterationsDecreased and must reset on changes to AllEvents and AllRels and NumOfCases and TraitsPriors</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors(bool initialise)
		{
			if (this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isDone&&((!initialise)||this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised)) {
				return ;
			}
			for(int Traits = 0; Traits<14; Traits++) {
				for(int Events = 0; Events<215; Events++) {
					for(int Rel = 0; Rel<3; Rel++) {
						this.DialogueCPT_uses_B[0][Events][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][Rel]);
					}
				}
			}
			// Create array for 'DialogueCPT_marginal' Forwards messages.
			this.DialogueCPT_marginal_F = new GibbsMarginal<DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>,Vector[][][]>(this.DialogueCPT_marginal_B, 100, 5, true, true, false);
			this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isDone = true;
			this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and NumOfCases and must reset on changes to AllEvents and AllRels and DialogueCPTPrior and TraitsPriors</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised)) {
				return ;
			}
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				for(int Traits = 0; Traits<14; Traits++) {
					this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits] = new GibbsMarginal<Discrete,int>(Discrete.Uniform(670), 100, 5, false, false, false);
				}
			}
			// Create array for 'AllTraits_marginal' Forwards messages.
			this.AllTraits_marginal_F = new GibbsMarginal<DistributionRefArray<Discrete,int>,int[]>(this.AllTraits_marginal_B, 100, 5, false, false, false);
			// Create array for 'DialogueChild_marginal' Forwards messages.
			this.DialogueChild_marginal_F = new GibbsMarginal<DistributionRefArray<Discrete,int>,int[]>(this.DialogueChild_marginal_B, 100, 5, true, true, false);
			this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isDone = true;
			this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and TraitsPriors and must reset on changes to AllEvents and AllRels and DialogueCPTPrior and NumOfCases</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised)) {
				return ;
			}
			this.PossibleTraits_marginal_F = new GibbsMarginal<Dirichlet,Vector>(this.TraitsPriors, 100, 5, false, false, false);
			this.PossibleTraits_uses_B[0] = ArrayHelper.MakeUniform<Dirichlet>(this.TraitsPriors);
			this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isDone = true;
			this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of NumOfCases</summary>
		private void Changed_NumOfCases()
		{
			if (this.Changed_NumOfCases_isDone) {
				return ;
			}
			// Create array for replicates of 'DialogueChild_NCases__Traits_marginal_F'
			this.DialogueChild_NCases__Traits_marginal_F = new GibbsMarginal<Discrete,int>[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for replicates of 'DialogueChild_NCases__Traits_marginal_F'
				this.DialogueChild_NCases__Traits_marginal_F[NCases] = new GibbsMarginal<Discrete,int>[14];
			}
			this.AllTraits_marginal_B_reduced = default(Discrete);
			if (this.NumOfCases>0) {
				this.AllTraits_marginal_B_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
			}
			// Create array for 'AllTraits_marginal' Backwards messages.
			this.AllTraits_marginal_B = new DistributionRefArray<Discrete,int>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				this.AllTraits_marginal_B[NCases] = this.AllTraits_marginal_B_reduced;
			}
			this.DialogueChild_marginal_B_reduced = default(Discrete);
			if (this.NumOfCases>0) {
				this.DialogueChild_marginal_B_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(670));
			}
			// Create array for 'DialogueChild_marginal' Backwards messages.
			this.DialogueChild_marginal_B = new DistributionRefArray<Discrete,int>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				this.DialogueChild_marginal_B[NCases] = this.DialogueChild_marginal_B_reduced;
			}
			this.Changed_NumOfCases_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			// Create array for 'PossibleTraits_uses' Backwards messages.
			this.PossibleTraits_uses_B = new Dirichlet[1];
			// Create array for 'DialogueCPT_uses' Backwards messages.
			this.DialogueCPT_uses_B = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>[1];
			// Create array for 'DialogueCPT_uses' Backwards messages.
			this.DialogueCPT_uses_B[0] = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(215);
			for(int Events = 0; Events<215; Events++) {
				// Create array for 'DialogueCPT_uses' Backwards messages.
				this.DialogueCPT_uses_B[0][Events] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(14);
			}
			for(int Traits = 0; Traits<14; Traits++) {
				for(int Events = 0; Events<215; Events++) {
					// Create array for 'DialogueCPT_uses' Backwards messages.
					this.DialogueCPT_uses_B[0][Events][Traits] = new DistributionRefArray<Dirichlet,Vector>(3);
				}
			}
			// Create array for 'DialogueCPT_marginal' Backwards messages.
			this.DialogueCPT_marginal_B = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(215);
			for(int Events = 0; Events<215; Events++) {
				// Create array for 'DialogueCPT_marginal' Backwards messages.
				this.DialogueCPT_marginal_B[Events] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(14);
			}
			for(int Traits = 0; Traits<14; Traits++) {
				for(int Events = 0; Events<215; Events++) {
					// Create array for 'DialogueCPT_marginal' Backwards messages.
					this.DialogueCPT_marginal_B[Events][Traits] = new DistributionRefArray<Dirichlet,Vector>(3);
				}
			}
			this.Constant_isDone = true;
		}

		/// <summary>
		/// Returns the marginal distribution for 'DialogueChild' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> DialogueChildMarginal()
		{
			return ArrayHelper.MakeCopy<DistributionRefArray<Discrete,int>>(this.DialogueChild_marginal_F.Distribution);
		}

		/// <summary>
		/// Returns the Samples for 'DialogueChild' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The Samples</returns>
		public IList<int[]> DialogueChildSamples()
		{
			return new List<int[]>(this.DialogueChild_marginal_F.Samples);
		}

		/// <summary>
		/// Returns the marginal distribution for 'DialogueCPT' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPTMarginal()
		{
			return ArrayHelper.MakeCopy<DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>>(this.DialogueCPT_marginal_F.Distribution);
		}

		/// <summary>
		/// Returns the Samples for 'DialogueCPT' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The Samples</returns>
		public IList<Vector[][][]> DialogueCPTSamples()
		{
			return new List<Vector[][][]>(this.DialogueCPT_marginal_F.Samples);
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isDone = false;
					this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isDone = false;
					this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isDone = false;
				}
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
			}
			this.Constant();
			this.Changed_NumOfCases();
			this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors(initialise);
			this.Changed_DialogueCPTPrior();
			this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors(initialise);
			this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases(initialise);
			this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="NumOfCases") {
				return this.NumOfCases;
			}
			if (variableName=="EventsPriors") {
				return this.EventsPriors;
			}
			if (variableName=="TraitsPriors") {
				return this.TraitsPriors;
			}
			if (variableName=="RelStatusPriors") {
				return this.RelStatusPriors;
			}
			if (variableName=="DialogueCPTPrior") {
				return this.DialogueCPTPrior;
			}
			if (variableName=="AllEvents") {
				return this.AllEvents;
			}
			if (variableName=="AllRels") {
				return this.AllRels;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="DialogueChild") {
				return this.DialogueChildMarginal();
			}
			if (variableName=="DialogueCPT") {
				return this.DialogueCPTMarginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			if ((variableName=="DialogueChild")&&(query=="Samples")) {
				return this.DialogueChildSamples();
			}
			if ((variableName=="DialogueCPT")&&(query=="Samples")) {
				return this.DialogueCPTSamples();
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="NumOfCases") {
				this.NumOfCases = (int)value;
				return ;
			}
			if (variableName=="EventsPriors") {
				this.EventsPriors = (Dirichlet)value;
				return ;
			}
			if (variableName=="TraitsPriors") {
				this.TraitsPriors = (Dirichlet)value;
				return ;
			}
			if (variableName=="RelStatusPriors") {
				this.RelStatusPriors = (Dirichlet)value;
				return ;
			}
			if (variableName=="DialogueCPTPrior") {
				this.DialogueCPTPrior = (Dirichlet[][][])value;
				return ;
			}
			if (variableName=="AllEvents") {
				this.AllEvents = (int[])value;
				return ;
			}
			if (variableName=="AllRels") {
				this.AllRels = (int[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
