// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Factors;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2301.301 at 6:05 PM on Wednesday, August 9, 2023.
	/// </remarks>
	public partial class DialogueDirector_VMP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>Field backing the AllEvents property</summary>
		private int[] AllEvents_field;
		/// <summary>Field backing the AllRels property</summary>
		private int[] AllRels_field;
		/// <summary>Messages from uses of 'AllTraits_NCases__selector_cases_depth1'</summary>
		public Bernoulli[][][] AllTraits_NCases__selector_cases_depth1_uses_B;
		/// <summary>True if Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors has executed. Set this to false to force re-execution of Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors</summary>
		public bool Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone;
		/// <summary>True if Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors has executed. Set this to false to force re-execution of Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors</summary>
		public bool Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isDone;
		/// <summary>True if Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors has performed initialisation. Set this to false to force re-execution of Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors</summary>
		public bool Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isInitialised;
		/// <summary>True if Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors has executed. Set this to false to force re-execution of Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors</summary>
		public bool Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isDone;
		/// <summary>True if Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors has performed initialisation. Set this to false to force re-execution of Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors</summary>
		public bool Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isInitialised;
		/// <summary>True if Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors has executed. Set this to false to force re-execution of Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors</summary>
		public bool Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isDone;
		/// <summary>True if Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors has performed initialisation. Set this to false to force re-execution of Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors</summary>
		public bool Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised;
		/// <summary>True if Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors</summary>
		public bool Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors</summary>
		public bool Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised;
		/// <summary>True if Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases has executed. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases</summary>
		public bool Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isDone;
		/// <summary>True if Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases has performed initialisation. Set this to false to force re-execution of Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases</summary>
		public bool Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised;
		/// <summary>True if Changed_NumOfCases has executed. Set this to false to force re-execution of Changed_NumOfCases</summary>
		public bool Changed_NumOfCases_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		public DistributionRefArray<Discrete,int> DialogueChild_F;
		public Discrete[][] DialogueChild_NCases__Traits_F;
		/// <summary>Message to marginal of 'DialogueChild_NCases__Traits'</summary>
		public Discrete[][] DialogueChild_NCases__Traits_marginal_F;
		public Discrete DialogueChild_use_B_reduced;
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPT_itemAllEvents_NCases__F;
		/// <summary>Message to marginal of 'DialogueCPT'</summary>
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPT_marginal_F;
		/// <summary>Message from use of 'DialogueCPT'</summary>
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPT_use_B;
		/// <summary>Field backing the DialogueCPTPrior property</summary>
		private Dirichlet[][][] DialogueCPTPrior_field;
		/// <summary>Field backing the EventsPriors property</summary>
		private Dirichlet EventsPriors_field;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Field backing the NumOfCases property</summary>
		private int NumOfCases_field;
		/// <summary>Message from use of 'PossibleTraits'</summary>
		public Dirichlet PossibleTraits_use_B;
		/// <summary>Field backing the RelStatusPriors property</summary>
		private Dirichlet RelStatusPriors_field;
		/// <summary>Field backing the TraitsPriors property</summary>
		private Dirichlet TraitsPriors_field;
		#endregion

		#region Properties
		/// <summary>The externally-specified value of 'AllEvents'</summary>
		public int[] AllEvents
		{
			get {
				return this.AllEvents_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.NumOfCases)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.NumOfCases)+" was expected for variable \'AllEvents\'");
				}
				this.AllEvents_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised = false;
				this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isDone = false;
				this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isDone = false;
				this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'AllRels'</summary>
		public int[] AllRels
		{
			get {
				return this.AllRels_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.NumOfCases)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.NumOfCases)+" was expected for variable \'AllRels\'");
				}
				this.AllRels_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised = false;
				this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isDone = false;
				this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'DialogueCPTPrior'</summary>
		public Dirichlet[][][] DialogueCPTPrior
		{
			get {
				return this.DialogueCPTPrior_field;
			}
			set {
				if ((value!=null)&&(value.Length!=215)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+215)+" was expected for variable \'DialogueCPTPrior\'");
				}
				this.DialogueCPTPrior_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isDone = false;
				this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isDone = false;
				this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isDone = false;
				this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'EventsPriors'</summary>
		public Dirichlet EventsPriors
		{
			get {
				return this.EventsPriors_field;
			}
			set {
				this.EventsPriors_field = value;
				this.numberOfIterationsDone = 0;
			}
		}

		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'NumOfCases'</summary>
		public int NumOfCases
		{
			get {
				return this.NumOfCases_field;
			}
			set {
				if (this.NumOfCases_field!=value) {
					this.NumOfCases_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised = false;
					this.Changed_NumOfCases_isDone = false;
					this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isDone = false;
					this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isDone = false;
					this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isDone = false;
					this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised = false;
					this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
				}
			}
		}

		/// <summary>The externally-specified value of 'RelStatusPriors'</summary>
		public Dirichlet RelStatusPriors
		{
			get {
				return this.RelStatusPriors_field;
			}
			set {
				this.RelStatusPriors_field = value;
				this.numberOfIterationsDone = 0;
			}
		}

		/// <summary>The externally-specified value of 'TraitsPriors'</summary>
		public Dirichlet TraitsPriors
		{
			get {
				return this.TraitsPriors_field;
			}
			set {
				this.TraitsPriors_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised = false;
				this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isInitialised = false;
				this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isDone = false;
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of AllEvents and AllRels and DialogueCPTPrior and numberOfIterations and NumOfCases and TraitsPriors</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors(int numberOfIterations)
		{
			if (this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone) {
				return ;
			}
			Dirichlet PossibleTraits_marginal_F = ArrayHelper.MakeUniform<Dirichlet>(this.TraitsPriors);
			Discrete AllTraits_F_reduced;
			AllTraits_F_reduced = default(Discrete);
			if (this.NumOfCases>0) {
				AllTraits_F_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
			}
			// Create array for replicates of 'AllTraits_NCases__selector_uses_B'
			Discrete[][] AllTraits_NCases__selector_uses_B = new Discrete[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_uses' Backwards messages.
				AllTraits_NCases__selector_uses_B[NCases] = new Discrete[2];
				AllTraits_NCases__selector_uses_B[NCases][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
				AllTraits_NCases__selector_uses_B[NCases][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
			}
			// Create array for replicates of 'AllTraits_NCases__selector_cases_uses_B'
			DistributionStructArray<Bernoulli,bool>[][] AllTraits_NCases__selector_cases_uses_B = new DistributionStructArray<Bernoulli,bool>[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases] = new DistributionStructArray<Bernoulli,bool>[2];
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases][1] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_uses_B[NCases][1][Traits] = Bernoulli.Uniform();
				}
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases][0] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_uses_B[NCases][0][Traits] = Bernoulli.Uniform();
					this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][7] = Bernoulli.Uniform();
					this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][4] = Bernoulli.Uniform();
					this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][3] = Bernoulli.Uniform();
					this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][2] = Bernoulli.Uniform();
					this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][1] = Bernoulli.Uniform();
					this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][0] = Bernoulli.Uniform();
					this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][5] = Bernoulli.Uniform();
				}
			}
			DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPT_itemAllEvents_NCases__B;
			// Create array for 'DialogueCPT_itemAllEvents_NCases_' Backwards messages.
			DialogueCPT_itemAllEvents_NCases__B = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'DialogueCPT_itemAllEvents_NCases_' Backwards messages.
				DialogueCPT_itemAllEvents_NCases__B[NCases] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					// Create array for 'DialogueCPT_itemAllEvents_NCases_' Backwards messages.
					DialogueCPT_itemAllEvents_NCases__B[NCases][Traits] = new DistributionRefArray<Dirichlet,Vector>(3);
					for(int Rel = 0; Rel<3; Rel++) {
						DialogueCPT_itemAllEvents_NCases__B[NCases][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[this.AllEvents[NCases]][Traits][Rel]);
					}
				}
			}
			// Create array for replicates of 'DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B'
			Dirichlet[][] DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B = new Dirichlet[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for replicates of 'DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B'
				DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B[NCases] = new Dirichlet[14];
				for(int Traits = 0; Traits<14; Traits++) {
					DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B[NCases][Traits] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[this.AllEvents[NCases]][Traits][this.AllRels[NCases]]);
				}
			}
			// Create array for replicates of 'AllTraits_NCases__selector_cases_depth1_B'
			DistributionStructArray<Bernoulli,bool>[] AllTraits_NCases__selector_cases_depth1_B = new DistributionStructArray<Bernoulli,bool>[this.NumOfCases];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_cases_depth1' Backwards messages.
				AllTraits_NCases__selector_cases_depth1_B[NCases] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_depth1_B[NCases][Traits] = Bernoulli.Uniform();
				}
			}
			// Create array for replicates of 'AllTraits_NCases__selector_cases_B'
			DistributionStructArray<Bernoulli,bool>[] AllTraits_NCases__selector_cases_B = new DistributionStructArray<Bernoulli,bool>[this.NumOfCases];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_cases' Backwards messages.
				AllTraits_NCases__selector_cases_B[NCases] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_B[NCases][Traits] = Bernoulli.Uniform();
				}
			}
			// Create array for replicates of 'AllTraits_NCases__selector_B'
			Discrete[] AllTraits_NCases__selector_B = new Discrete[this.NumOfCases];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				AllTraits_NCases__selector_B[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
			}
			DistributionRefArray<Discrete,int> AllTraits_marginal_F;
			// Create array for 'AllTraits_marginal' Forwards messages.
			AllTraits_marginal_F = new DistributionRefArray<Discrete,int>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				AllTraits_marginal_F[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(14));
			}
			Dirichlet[] PossibleTraits_rep_B;
			// Create array for 'PossibleTraits_rep' Backwards messages.
			PossibleTraits_rep_B = new Dirichlet[this.NumOfCases];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				PossibleTraits_rep_B[NCases] = ArrayHelper.MakeUniform<Dirichlet>(this.TraitsPriors);
			}
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				// Message to 'PossibleTraits_marginal' from Variable factor
				PossibleTraits_marginal_F = VariableVmpOp<Vector>.MarginalAverageLogarithm<Dirichlet>(this.PossibleTraits_use_B, this.TraitsPriors, PossibleTraits_marginal_F);
				for(int Traits = 0; Traits<14; Traits++) {
					for(int Events = 0; Events<215; Events++) {
						for(int Rel = 0; Rel<3; Rel++) {
							// Message to 'DialogueCPT_marginal' from Variable factor
							this.DialogueCPT_marginal_F[Events][Traits][Rel] = VariableVmpOp<Vector>.MarginalAverageLogarithm<Dirichlet>(this.DialogueCPT_use_B[Events][Traits][Rel], this.DialogueCPTPrior[Events][Traits][Rel], this.DialogueCPT_marginal_F[Events][Traits][Rel]);
						}
					}
				}
				if (this.NumOfCases>0) {
					// Message to 'AllTraits' from Discrete factor
					AllTraits_F_reduced = DiscreteFromDirichletOp.SampleAverageLogarithm(PossibleTraits_marginal_F, AllTraits_F_reduced);
				}
				for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
					// Message to 'DialogueCPT_itemAllEvents_NCases_' from GetItems factor
					this.DialogueCPT_itemAllEvents_NCases__F[NCases] = GetItemsOp<Vector[][]>.ItemsAverageLogarithm<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>>(this.DialogueCPT_marginal_F, this.AllEvents, NCases, this.DialogueCPT_itemAllEvents_NCases__F[NCases]);
					for(int Traits = 0; Traits<14; Traits++) {
						// Message to 'AllTraits_NCases__selector_cases_depth1_uses' from Discrete factor
						this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][5] = Bernoulli.FromLogOdds(DiscreteFromDirichletOp.AverageLogFactor(this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits], this.DialogueCPT_itemAllEvents_NCases__F[NCases][Traits][this.AllRels[NCases]]));
						// Message to 'AllTraits_NCases__selector_cases_depth1' from Replicate factor
						AllTraits_NCases__selector_cases_depth1_B[NCases][Traits] = ReplicateOp.DefAverageLogarithm<Bernoulli>(this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits], AllTraits_NCases__selector_cases_depth1_B[NCases][Traits]);
						// Message to 'AllTraits_NCases__selector_cases_uses' from Copy factor
						AllTraits_NCases__selector_cases_uses_B[NCases][0][Traits] = ArrayHelper.SetTo<Bernoulli>(AllTraits_NCases__selector_cases_uses_B[NCases][0][Traits], AllTraits_NCases__selector_cases_depth1_B[NCases][Traits]);
					}
					// Message to 'AllTraits_NCases__selector_cases' from Replicate factor
					AllTraits_NCases__selector_cases_B[NCases] = ReplicateOp.DefAverageLogarithm<DistributionStructArray<Bernoulli,bool>>(AllTraits_NCases__selector_cases_uses_B[NCases], AllTraits_NCases__selector_cases_B[NCases]);
					// Message to 'AllTraits_NCases__selector_uses' from CasesInt factor
					AllTraits_NCases__selector_uses_B[NCases][0] = IntCasesOp.IAverageLogarithm(AllTraits_NCases__selector_cases_B[NCases], AllTraits_NCases__selector_uses_B[NCases][0]);
					// Message to 'AllTraits_NCases__selector' from Replicate factor
					AllTraits_NCases__selector_B[NCases] = ReplicateOp.DefAverageLogarithm<Discrete>(AllTraits_NCases__selector_uses_B[NCases], AllTraits_NCases__selector_B[NCases]);
					// Message to 'AllTraits_marginal' from Variable factor
					AllTraits_marginal_F[NCases] = VariableVmpOp<int>.MarginalAverageLogarithm<Discrete>(AllTraits_NCases__selector_B[NCases], AllTraits_F_reduced, AllTraits_marginal_F[NCases]);
					for(int Traits = 0; Traits<14; Traits++) {
						// Message to 'DialogueChild_NCases__Traits' from Discrete factor
						this.DialogueChild_NCases__Traits_F[NCases][Traits] = DiscreteFromDirichletOp.SampleAverageLogarithm(this.DialogueCPT_itemAllEvents_NCases__F[NCases][Traits][this.AllRels[NCases]], this.DialogueChild_NCases__Traits_F[NCases][Traits]);
						// Message to 'DialogueChild_NCases__Traits_marginal' from Variable factor
						this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits] = VariableVmpOp<int>.MarginalAverageLogarithm<Discrete>(this.DialogueChild_use_B_reduced, this.DialogueChild_NCases__Traits_F[NCases][Traits], this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits]);
					}
					// Message to 'PossibleTraits_rep' from Discrete factor
					PossibleTraits_rep_B[NCases] = DiscreteFromDirichletOp.ProbsAverageLogarithm(AllTraits_marginal_F[NCases], PossibleTraits_rep_B[NCases]);
				}
				// Message to 'PossibleTraits_use' from Replicate factor
				this.PossibleTraits_use_B = ReplicateOp.DefAverageLogarithm<Dirichlet>(PossibleTraits_rep_B, this.PossibleTraits_use_B);
				for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
					for(int Traits = 0; Traits<14; Traits++) {
						// Message to 'AllTraits_NCases__selector_cases_depth1_uses' from Variable factor
						this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][6] = Bernoulli.FromLogOdds(VariableVmpOp<int>.AverageLogFactor<Discrete>(this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits]));
						// Message to 'DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases__' from Discrete factor
						DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B[NCases][Traits] = DiscreteFromDirichletOp.ProbsAverageLogarithm(this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits], DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B[NCases][Traits]);
						// Message to 'DialogueCPT_itemAllEvents_NCases_' from EnterOne factor
						DialogueCPT_itemAllEvents_NCases__B[NCases][Traits][this.AllRels[NCases]] = GateEnterOneOp<Vector>.ValueAverageLogarithm<Dirichlet>(DialogueCPT_AllEvents_NCases__Traits_AllRels_NCases___B[NCases][Traits], AllTraits_marginal_F[NCases], Traits, DialogueCPT_itemAllEvents_NCases__B[NCases][Traits][this.AllRels[NCases]]);
					}
				}
				// Message to 'DialogueCPT_use' from GetItems factor
				this.DialogueCPT_use_B = GetItemsOp<Vector[][]>.ArrayAverageLogarithm<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>>(DialogueCPT_itemAllEvents_NCases__B, this.AllEvents, this.DialogueCPT_use_B);
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			for(int Traits = 0; Traits<14; Traits++) {
				for(int Events = 0; Events<215; Events++) {
					for(int Rel = 0; Rel<3; Rel++) {
						// Message to 'DialogueCPT_marginal' from Variable factor
						this.DialogueCPT_marginal_F[Events][Traits][Rel] = VariableVmpOp<Vector>.MarginalAverageLogarithm<Dirichlet>(this.DialogueCPT_use_B[Events][Traits][Rel], this.DialogueCPTPrior[Events][Traits][Rel], this.DialogueCPT_marginal_F[Events][Traits][Rel]);
					}
				}
			}
			// Create array for 'DialogueChild' Forwards messages.
			this.DialogueChild_F = new DistributionRefArray<Discrete,int>(this.NumOfCases);
			// Create array for replicates of 'AllTraits_NCases__selector_cases_F'
			DistributionStructArray<Bernoulli,bool>[] AllTraits_NCases__selector_cases_F = new DistributionStructArray<Bernoulli,bool>[this.NumOfCases];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				this.DialogueChild_F[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(670));
				// Create array for 'AllTraits_NCases__selector_cases' Forwards messages.
				AllTraits_NCases__selector_cases_F[NCases] = new DistributionStructArray<Bernoulli,bool>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					AllTraits_NCases__selector_cases_F[NCases][Traits] = Bernoulli.Uniform();
					// Message to 'AllTraits_NCases__selector_cases' from CasesInt factor
					AllTraits_NCases__selector_cases_F[NCases][Traits] = IntCasesOp.CasesAverageLogarithm(AllTraits_marginal_F[NCases], Traits);
				}
				// Message to 'DialogueChild' from Exit factor
				this.DialogueChild_F[NCases] = GateExitOp<int>.ExitAverageLogarithm<Discrete>(AllTraits_NCases__selector_cases_F[NCases], this.DialogueChild_NCases__Traits_marginal_F[NCases], this.DialogueChild_F[NCases]);
			}
			this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of AllEvents and AllRels and DialogueCPTPrior and numberOfIterationsDecreased and NumOfCases and must reset on changes to TraitsPriors</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors(bool initialise)
		{
			if (this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isDone&&((!initialise)||this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isInitialised)) {
				return ;
			}
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				for(int Traits = 0; Traits<14; Traits++) {
					// Message to 'DialogueChild_NCases__Traits' from Discrete factor
					this.DialogueChild_NCases__Traits_F[NCases][Traits] = DiscreteFromDirichletOp.SampleAverageLogarithm(this.DialogueCPT_itemAllEvents_NCases__F[NCases][Traits][this.AllRels[NCases]], this.DialogueChild_NCases__Traits_F[NCases][Traits]);
					// Message to 'DialogueChild_NCases__Traits_marginal' from Variable factor
					this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits] = VariableVmpOp<int>.MarginalAverageLogarithm<Discrete>(this.DialogueChild_use_B_reduced, this.DialogueChild_NCases__Traits_F[NCases][Traits], this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits]);
					// Message to 'AllTraits_NCases__selector_cases_depth1_uses' from Variable factor
					this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][6] = Bernoulli.FromLogOdds(VariableVmpOp<int>.AverageLogFactor<Discrete>(this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits]));
				}
			}
			this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isDone = true;
			this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of AllEvents and DialogueCPTPrior and numberOfIterationsDecreased and NumOfCases and must reset on changes to AllRels and TraitsPriors</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors(bool initialise)
		{
			if (this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isDone&&((!initialise)||this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isInitialised)) {
				return ;
			}
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				for(int Traits = 0; Traits<14; Traits++) {
					for(int Rel = 0; Rel<3; Rel++) {
						this.DialogueCPT_itemAllEvents_NCases__F[NCases][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[this.AllEvents[NCases]][Traits][Rel]);
					}
				}
				// Message to 'DialogueCPT_itemAllEvents_NCases_' from GetItems factor
				this.DialogueCPT_itemAllEvents_NCases__F[NCases] = GetItemsOp<Vector[][]>.ItemsAverageLogarithm<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>>(this.DialogueCPT_marginal_F, this.AllEvents, NCases, this.DialogueCPT_itemAllEvents_NCases__F[NCases]);
			}
			this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isDone = true;
			this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of DialogueCPTPrior and numberOfIterationsDecreased and must reset on changes to AllEvents and AllRels and NumOfCases and TraitsPriors</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors(bool initialise)
		{
			if (this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isDone&&((!initialise)||this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised)) {
				return ;
			}
			for(int Traits = 0; Traits<14; Traits++) {
				for(int Events = 0; Events<215; Events++) {
					for(int Rel = 0; Rel<3; Rel++) {
						this.DialogueCPT_use_B[Events][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][Rel]);
						this.DialogueCPT_marginal_F[Events][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][Rel]);
						// Message to 'DialogueCPT_marginal' from Variable factor
						this.DialogueCPT_marginal_F[Events][Traits][Rel] = VariableVmpOp<Vector>.MarginalAverageLogarithm<Dirichlet>(this.DialogueCPT_use_B[Events][Traits][Rel], this.DialogueCPTPrior[Events][Traits][Rel], this.DialogueCPT_marginal_F[Events][Traits][Rel]);
					}
				}
			}
			this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isDone = true;
			this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and NumOfCases and must reset on changes to AllEvents and AllRels and DialogueCPTPrior and TraitsPriors</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised)) {
				return ;
			}
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				for(int Traits = 0; Traits<14; Traits++) {
					this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits][6] = Bernoulli.Uniform();
					this.DialogueChild_NCases__Traits_F[NCases][Traits] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(670));
					this.DialogueChild_NCases__Traits_marginal_F[NCases][Traits] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(670));
				}
			}
			this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isDone = true;
			this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of numberOfIterationsDecreased and TraitsPriors and must reset on changes to AllEvents and AllRels and DialogueCPTPrior and NumOfCases</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases(bool initialise)
		{
			if (this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isDone&&((!initialise)||this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised)) {
				return ;
			}
			this.PossibleTraits_use_B = ArrayHelper.MakeUniform<Dirichlet>(this.TraitsPriors);
			this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isDone = true;
			this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of NumOfCases</summary>
		private void Changed_NumOfCases()
		{
			if (this.Changed_NumOfCases_isDone) {
				return ;
			}
			// Create array for replicates of 'AllTraits_NCases__selector_cases_depth1_uses_B'
			this.AllTraits_NCases__selector_cases_depth1_uses_B = new Bernoulli[this.NumOfCases][][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_cases_depth1_uses' Backwards messages.
				this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases] = new Bernoulli[14][];
				for(int Traits = 0; Traits<14; Traits++) {
					// Create array for 'AllTraits_NCases__selector_cases_depth1_uses' Backwards messages.
					this.AllTraits_NCases__selector_cases_depth1_uses_B[NCases][Traits] = new Bernoulli[8];
				}
			}
			this.DialogueChild_use_B_reduced = default(Discrete);
			if (this.NumOfCases>0) {
				this.DialogueChild_use_B_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(670));
			}
			// Create array for replicates of 'DialogueChild_NCases__Traits_F'
			this.DialogueChild_NCases__Traits_F = new Discrete[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for replicates of 'DialogueChild_NCases__Traits_F'
				this.DialogueChild_NCases__Traits_F[NCases] = new Discrete[14];
			}
			// Create array for replicates of 'DialogueChild_NCases__Traits_marginal_F'
			this.DialogueChild_NCases__Traits_marginal_F = new Discrete[this.NumOfCases][];
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for replicates of 'DialogueChild_NCases__Traits_marginal_F'
				this.DialogueChild_NCases__Traits_marginal_F[NCases] = new Discrete[14];
			}
			// Create array for 'DialogueCPT_itemAllEvents_NCases_' Forwards messages.
			this.DialogueCPT_itemAllEvents_NCases__F = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(this.NumOfCases);
			for(int NCases = 0; NCases<this.NumOfCases; NCases++) {
				// Create array for 'DialogueCPT_itemAllEvents_NCases_' Forwards messages.
				this.DialogueCPT_itemAllEvents_NCases__F[NCases] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(14);
				for(int Traits = 0; Traits<14; Traits++) {
					// Create array for 'DialogueCPT_itemAllEvents_NCases_' Forwards messages.
					this.DialogueCPT_itemAllEvents_NCases__F[NCases][Traits] = new DistributionRefArray<Dirichlet,Vector>(3);
				}
			}
			this.Changed_NumOfCases_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			// Create array for 'DialogueCPT_use' Backwards messages.
			this.DialogueCPT_use_B = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(215);
			for(int Events = 0; Events<215; Events++) {
				// Create array for 'DialogueCPT_use' Backwards messages.
				this.DialogueCPT_use_B[Events] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(14);
			}
			for(int Traits = 0; Traits<14; Traits++) {
				for(int Events = 0; Events<215; Events++) {
					// Create array for 'DialogueCPT_use' Backwards messages.
					this.DialogueCPT_use_B[Events][Traits] = new DistributionRefArray<Dirichlet,Vector>(3);
				}
			}
			// Create array for 'DialogueCPT_marginal' Forwards messages.
			this.DialogueCPT_marginal_F = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(215);
			for(int Events = 0; Events<215; Events++) {
				// Create array for 'DialogueCPT_marginal' Forwards messages.
				this.DialogueCPT_marginal_F[Events] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(14);
			}
			for(int Traits = 0; Traits<14; Traits++) {
				for(int Events = 0; Events<215; Events++) {
					// Create array for 'DialogueCPT_marginal' Forwards messages.
					this.DialogueCPT_marginal_F[Events][Traits] = new DistributionRefArray<Dirichlet,Vector>(3);
				}
			}
			this.Constant_isDone = true;
		}

		/// <summary>
		/// Returns the marginal distribution for 'DialogueChild' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> DialogueChildMarginal()
		{
			return this.DialogueChild_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'DialogueCPT' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPTMarginal()
		{
			return ArrayHelper.MakeCopy<DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>>(this.DialogueCPT_marginal_F);
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors_isDone = false;
					this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors_isDone = false;
					this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors_isDone = false;
					this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors_isDone = false;
					this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases_isDone = false;
				}
				this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors_isDone = false;
			}
			this.Constant();
			this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllEvents_AllRels_NumOfCases_TraitsPriors(initialise);
			this.Changed_NumOfCases();
			this.Changed_AllEvents_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_AllRels_TraitsPriors(initialise);
			this.Changed_numberOfIterationsDecreased_NumOfCases_Init_AllEvents_AllRels_DialogueCPTPrior_TraitsPriors(initialise);
			this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterationsDecreased_NumOfCases_Init_TraitsPriors(initialise);
			this.Changed_numberOfIterationsDecreased_TraitsPriors_Init_AllEvents_AllRels_DialogueCPTPrior_NumOfCases(initialise);
			this.Changed_AllEvents_AllRels_DialogueCPTPrior_numberOfIterations_NumOfCases_TraitsPriors(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="NumOfCases") {
				return this.NumOfCases;
			}
			if (variableName=="EventsPriors") {
				return this.EventsPriors;
			}
			if (variableName=="TraitsPriors") {
				return this.TraitsPriors;
			}
			if (variableName=="RelStatusPriors") {
				return this.RelStatusPriors;
			}
			if (variableName=="DialogueCPTPrior") {
				return this.DialogueCPTPrior;
			}
			if (variableName=="AllEvents") {
				return this.AllEvents;
			}
			if (variableName=="AllRels") {
				return this.AllRels;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="DialogueCPT") {
				return this.DialogueCPTMarginal();
			}
			if (variableName=="DialogueChild") {
				return this.DialogueChildMarginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="NumOfCases") {
				this.NumOfCases = (int)value;
				return ;
			}
			if (variableName=="EventsPriors") {
				this.EventsPriors = (Dirichlet)value;
				return ;
			}
			if (variableName=="TraitsPriors") {
				this.TraitsPriors = (Dirichlet)value;
				return ;
			}
			if (variableName=="RelStatusPriors") {
				this.RelStatusPriors = (Dirichlet)value;
				return ;
			}
			if (variableName=="DialogueCPTPrior") {
				this.DialogueCPTPrior = (Dirichlet[][][])value;
				return ;
			}
			if (variableName=="AllEvents") {
				this.AllEvents = (int[])value;
				return ;
			}
			if (variableName=="AllRels") {
				this.AllRels = (int[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
