// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Math;
using Microsoft.ML.Probabilistic.Collections;
using Microsoft.ML.Probabilistic.Factors;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.4.2301.301 at 6:14 PM on Tuesday, May 16, 2023.
	/// </remarks>
	public partial class Model12_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>Message to marginal of 'AllEvents'</summary>
		public DistributionRefArray<Discrete,int> AllEvents_marginal_F;
		public DistributionStructArray<Bernoulli,bool>[][] AllEvents_NCases__Traits_selector_cases_B;
		/// <summary>Messages from uses of 'AllEvents_NCases__Traits_selector_cases'</summary>
		public Bernoulli[][][][] AllEvents_NCases__Traits_selector_cases_uses_B;
		/// <summary>Field backing the AllRels property</summary>
		private int[] AllRels_field;
		/// <summary>Message to marginal of 'AllRels'</summary>
		public DistributionRefArray<Discrete,int> AllRels_marginal_F;
		/// <summary>Message to marginal of 'AllTraits'</summary>
		public DistributionRefArray<Discrete,int> AllTraits_marginal_F;
		/// <summary>True if Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6 has executed. Set this to false to force re-execution of Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6</summary>
		public bool Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6_isDone;
		/// <summary>True if Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4 has executed. Set this to false to force re-execution of Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4</summary>
		public bool Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isDone;
		/// <summary>True if Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4 has performed initialisation. Set this to false to force re-execution of Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4</summary>
		public bool Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isInitialised;
		/// <summary>True if Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10 has executed. Set this to false to force re-execution of Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10</summary>
		public bool Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isDone;
		/// <summary>True if Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10 has performed initialisation. Set this to false to force re-execution of Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10</summary>
		public bool Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isInitialised;
		/// <summary>True if Changed_AllRels_NumberOfCases has executed. Set this to false to force re-execution of Changed_AllRels_NumberOfCases</summary>
		public bool Changed_AllRels_NumberOfCases_isDone;
		/// <summary>True if Changed_AllRels_NumberOfCases_RelStatusPriors has executed. Set this to false to force re-execution of Changed_AllRels_NumberOfCases_RelStatusPriors</summary>
		public bool Changed_AllRels_NumberOfCases_RelStatusPriors_isDone;
		/// <summary>True if Changed_DialogueCPTPrior has executed. Set this to false to force re-execution of Changed_DialogueCPTPrior</summary>
		public bool Changed_DialogueCPTPrior_isDone;
		/// <summary>True if Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5 has executed. Set this to false to force re-execution of Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5</summary>
		public bool Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isDone;
		/// <summary>True if Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5 has performed initialisation. Set this to false to force re-execution of Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5</summary>
		public bool Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isInitialised;
		/// <summary>True if Changed_EventsPriors has executed. Set this to false to force re-execution of Changed_EventsPriors</summary>
		public bool Changed_EventsPriors_isDone;
		/// <summary>True if Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8 has executed. Set this to false to force re-execution of Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8</summary>
		public bool Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isDone;
		/// <summary>True if Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8 has performed initialisation. Set this to false to force re-execution of Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8</summary>
		public bool Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isInitialised;
		/// <summary>True if Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9 has executed. Set this to false to force re-execution of Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9</summary>
		public bool Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isDone;
		/// <summary>True if Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9 has performed initialisation. Set this to false to force re-execution of Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9</summary>
		public bool Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isInitialised;
		/// <summary>True if Changed_NumberOfCases has executed. Set this to false to force re-execution of Changed_NumberOfCases</summary>
		public bool Changed_NumberOfCases_isDone;
		/// <summary>True if Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2 has executed. Set this to false to force re-execution of Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2</summary>
		public bool Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isDone;
		/// <summary>True if Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2 has performed initialisation. Set this to false to force re-execution of Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2</summary>
		public bool Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isInitialised;
		/// <summary>True if Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7 has executed. Set this to false to force re-execution of Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7</summary>
		public bool Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isDone;
		/// <summary>True if Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7 has performed initialisation. Set this to false to force re-execution of Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7</summary>
		public bool Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isInitialised;
		/// <summary>True if Changed_NumberOfCases_vint__6 has executed. Set this to false to force re-execution of Changed_NumberOfCases_vint__6</summary>
		public bool Changed_NumberOfCases_vint__6_isDone;
		/// <summary>True if Changed_RelStatusPriors has executed. Set this to false to force re-execution of Changed_RelStatusPriors</summary>
		public bool Changed_RelStatusPriors_isDone;
		/// <summary>True if Changed_TraitsPriors has executed. Set this to false to force re-execution of Changed_TraitsPriors</summary>
		public bool Changed_TraitsPriors_isDone;
		/// <summary>True if Constant has executed. Set this to false to force re-execution of Constant</summary>
		public bool Constant_isDone;
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPT_F;
		public DistributionRefArray<Dirichlet,Vector>[][] DialogueCPT_itemAllRels_NCases__B;
		public DistributionRefArray<Dirichlet,Vector>[][] DialogueCPT_itemAllRels_NCases__F;
		/// <summary>Message to marginal of 'DialogueCPT'</summary>
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPT_marginal_F;
		/// <summary>Message from use of 'DialogueCPT'</summary>
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPT_use_B;
		/// <summary>Buffer for GetItemsOp&lt;Vector&gt;.ItemsAverageConditional&lt;DistributionRefArray&lt;Dirichlet, Vector&gt;, Dirichlet&gt;</summary>
		public DistributionRefArray<Dirichlet,Vector>[][] DialogueCPT_use_F_Events__Traits__marginal;
		/// <summary>Field backing the DialogueCPTPrior property</summary>
		private Dirichlet[][][] DialogueCPTPrior_field;
		/// <summary>Message to marginal of 'DialogueCPTPrior'</summary>
		public PointMass<Dirichlet[][][]> DialogueCPTPrior_marginal_F;
		/// <summary>Field backing the EventsPriors property</summary>
		private Dirichlet EventsPriors_field;
		/// <summary>Message to marginal of 'EventsPriors'</summary>
		public PointMass<Dirichlet> EventsPriors_marginal_F;
		/// <summary>Field backing the NumberOfCases property</summary>
		private int NumberOfCases_field;
		/// <summary>Message to marginal of 'NumberOfCases'</summary>
		public PointMass<int> NumberOfCases_marginal_F;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Message to marginal of 'PossibleEvents'</summary>
		public Dirichlet PossibleEvents_marginal_F;
		public Dirichlet[] PossibleEvents_rep_B;
		/// <summary>Buffer for ReplicateOp_Divide.Marginal&lt;Dirichlet&gt;</summary>
		public Dirichlet PossibleEvents_rep_B_toDef;
		/// <summary>Message to marginal of 'PossibleRel'</summary>
		public Dirichlet PossibleRel_marginal_F;
		/// <summary>Message to marginal of 'PossibleTraits'</summary>
		public Dirichlet PossibleTraits_marginal_F;
		public Dirichlet[] PossibleTraits_rep_F;
		/// <summary>Field backing the RelStatusPriors property</summary>
		private Dirichlet RelStatusPriors_field;
		/// <summary>Message to marginal of 'RelStatusPriors'</summary>
		public PointMass<Dirichlet> RelStatusPriors_marginal_F;
		/// <summary>Field backing the TraitsPriors property</summary>
		private Dirichlet TraitsPriors_field;
		/// <summary>Message to marginal of 'TraitsPriors'</summary>
		public PointMass<Dirichlet> TraitsPriors_marginal_F;
		/// <summary>Field backing the vint__6 property</summary>
		private int[] vint__6_field;
		/// <summary>Message to marginal of 'vint__6'</summary>
		public DistributionRefArray<Discrete,int> vint__6_marginal_F;
		#endregion

		#region Properties
		/// <summary>The externally-specified value of 'AllRels'</summary>
		public int[] AllRels
		{
			get {
				return this.AllRels_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.NumberOfCases)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.NumberOfCases)+" was expected for variable \'AllRels\'");
				}
				this.AllRels_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_AllRels_NumberOfCases_isDone = false;
				this.Changed_AllRels_NumberOfCases_RelStatusPriors_isDone = false;
				this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isInitialised = false;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isInitialised = false;
				this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isInitialised = false;
				this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isDone = false;
				this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isDone = false;
				this.Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'DialogueCPTPrior'</summary>
		public Dirichlet[][][] DialogueCPTPrior
		{
			get {
				return this.DialogueCPTPrior_field;
			}
			set {
				if ((value!=null)&&(value.Length!=40)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+40)+" was expected for variable \'DialogueCPTPrior\'");
				}
				this.DialogueCPTPrior_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isInitialised = false;
				this.Changed_DialogueCPTPrior_isDone = false;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isDone = false;
				this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isInitialised = false;
				this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isDone = false;
				this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isDone = false;
				this.Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'EventsPriors'</summary>
		public Dirichlet EventsPriors
		{
			get {
				return this.EventsPriors_field;
			}
			set {
				this.EventsPriors_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_EventsPriors_isDone = false;
				this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isDone = false;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isInitialised = false;
				this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isDone = false;
				this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isInitialised = false;
				this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'NumberOfCases'</summary>
		public int NumberOfCases
		{
			get {
				return this.NumberOfCases_field;
			}
			set {
				if (this.NumberOfCases_field!=value) {
					this.NumberOfCases_field = value;
					this.numberOfIterationsDone = 0;
					this.Changed_NumberOfCases_vint__6_isDone = false;
					this.Changed_AllRels_NumberOfCases_isDone = false;
					this.Changed_AllRels_NumberOfCases_RelStatusPriors_isDone = false;
					this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isInitialised = false;
					this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isInitialised = false;
					this.Changed_NumberOfCases_isDone = false;
					this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isDone = false;
					this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isDone = false;
					this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isDone = false;
					this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isDone = false;
					this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isDone = false;
					this.Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6_isDone = false;
				}
			}
		}

		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'RelStatusPriors'</summary>
		public Dirichlet RelStatusPriors
		{
			get {
				return this.RelStatusPriors_field;
			}
			set {
				this.RelStatusPriors_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_RelStatusPriors_isDone = false;
				this.Changed_AllRels_NumberOfCases_RelStatusPriors_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'TraitsPriors'</summary>
		public Dirichlet TraitsPriors
		{
			get {
				return this.TraitsPriors_field;
			}
			set {
				this.TraitsPriors_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_TraitsPriors_isDone = false;
				this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isInitialised = false;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isInitialised = false;
				this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isInitialised = false;
				this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isDone = false;
				this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isInitialised = false;
				this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'vint__6'</summary>
		public int[] vint__6
		{
			get {
				return this.vint__6_field;
			}
			set {
				if ((value!=null)&&(value.Length!=this.NumberOfCases)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+this.NumberOfCases)+" was expected for variable \'vint__6\'");
				}
				this.vint__6_field = value;
				this.numberOfIterationsDone = 0;
				this.Changed_NumberOfCases_vint__6_isDone = false;
				this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isInitialised = false;
				this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isInitialised = false;
				this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isInitialised = false;
				this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isInitialised = false;
				this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isInitialised = false;
				this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isDone = false;
				this.Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>
		/// Returns the marginal distribution for 'AllEvents' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> AllEventsMarginal()
		{
			return this.AllEvents_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'AllRels' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> AllRelsMarginal()
		{
			return this.AllRels_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'AllTraits' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> AllTraitsMarginal()
		{
			return this.AllTraits_marginal_F;
		}

		/// <summary>Computations that depend on the observed value of AllRels and DialogueCPTPrior and EventsPriors and NumberOfCases and numberOfIterations and TraitsPriors and vint__6</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		private void Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6(int numberOfIterations)
		{
			if (this.Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6_isDone) {
				return ;
			}
			this.PossibleEvents_marginal_F = ArrayHelper.MakeUniform<Dirichlet>(this.EventsPriors);
			Dirichlet PossibleEvents_rep_F_marginal;
			PossibleEvents_rep_F_marginal = ReplicateOp_Divide.MarginalInit<Dirichlet>(this.EventsPriors);
			Dirichlet[] PossibleEvents_rep_F;
			// Create array for 'PossibleEvents_rep' Forwards messages.
			PossibleEvents_rep_F = new Dirichlet[this.NumberOfCases];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				PossibleEvents_rep_F[NCases] = ArrayHelper.MakeUniform<Dirichlet>(this.EventsPriors);
			}
			DistributionRefArray<Discrete,int> AllEvents_F;
			// Create array for 'AllEvents' Forwards messages.
			AllEvents_F = new DistributionRefArray<Discrete,int>(this.NumberOfCases);
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				AllEvents_F[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(40));
			}
			// Create array for replicates of 'AllTraits_NCases__selector_uses_B'
			Discrete[][] AllTraits_NCases__selector_uses_B = new Discrete[this.NumberOfCases][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_uses' Backwards messages.
				AllTraits_NCases__selector_uses_B[NCases] = new Discrete[3];
				AllTraits_NCases__selector_uses_B[NCases][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(13));
				AllTraits_NCases__selector_uses_B[NCases][2] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(13));
				AllTraits_NCases__selector_uses_B[NCases][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(13));
			}
			// Create array for replicates of 'AllTraits_NCases__selector_cases_uses_B'
			Bernoulli[][][] AllTraits_NCases__selector_cases_uses_B = new Bernoulli[this.NumberOfCases][][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
				AllTraits_NCases__selector_cases_uses_B[NCases] = new Bernoulli[13][];
				for(int Traits = 0; Traits<13; Traits++) {
					// Create array for 'AllTraits_NCases__selector_cases_uses' Backwards messages.
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits] = new Bernoulli[14];
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][13] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][12] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][11] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][10] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][9] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][8] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][7] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][4] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][3] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][2] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][1] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][0] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][5] = Bernoulli.Uniform();
					AllTraits_NCases__selector_cases_uses_B[NCases][Traits][6] = Bernoulli.Uniform();
				}
			}
			// Create array for replicates of 'AllEvents_NCases__Traits_selector_uses_B'
			Discrete[][][] AllEvents_NCases__Traits_selector_uses_B = new Discrete[this.NumberOfCases][][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllEvents_NCases__Traits_selector_uses_B'
				AllEvents_NCases__Traits_selector_uses_B[NCases] = new Discrete[13][];
				for(int Traits = 0; Traits<13; Traits++) {
					// Create array for 'AllEvents_NCases__Traits_selector_uses' Backwards messages.
					AllEvents_NCases__Traits_selector_uses_B[NCases][Traits] = new Discrete[2];
					AllEvents_NCases__Traits_selector_uses_B[NCases][Traits][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(40));
					AllEvents_NCases__Traits_selector_uses_B[NCases][Traits][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(40));
				}
			}
			// Create array for replicates of 'AllEvents_NCases__Traits_selector_uses_F'
			Discrete[][][] AllEvents_NCases__Traits_selector_uses_F = new Discrete[this.NumberOfCases][][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllEvents_NCases__Traits_selector_uses_F'
				AllEvents_NCases__Traits_selector_uses_F[NCases] = new Discrete[13][];
				for(int Traits = 0; Traits<13; Traits++) {
					// Create array for 'AllEvents_NCases__Traits_selector_uses' Forwards messages.
					AllEvents_NCases__Traits_selector_uses_F[NCases][Traits] = new Discrete[2];
					AllEvents_NCases__Traits_selector_uses_F[NCases][Traits][0] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(40));
					AllEvents_NCases__Traits_selector_uses_F[NCases][Traits][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(40));
				}
			}
			Discrete AllTraits_NCases__selector_rep_rep_B_reduced = default(Discrete);
			if (this.NumberOfCases>0) {
				AllTraits_NCases__selector_rep_rep_B_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(13));
			}
			// Create array for replicates of 'AllTraits_NCases__selector_uses_F'
			Discrete[][] AllTraits_NCases__selector_uses_F = new Discrete[this.NumberOfCases][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_uses' Forwards messages.
				AllTraits_NCases__selector_uses_F[NCases] = new Discrete[3];
				AllTraits_NCases__selector_uses_F[NCases][2] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(13));
				AllTraits_NCases__selector_uses_F[NCases][1] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(13));
			}
			// Create array for replicates of 'AllTraits_NCases__selector_rep_B_toDef'
			Discrete[] AllTraits_NCases__selector_rep_B_toDef = new Discrete[this.NumberOfCases];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				AllTraits_NCases__selector_rep_B_toDef[NCases] = ReplicateOp_Divide.ToDefInit<Discrete>(AllTraits_NCases__selector_uses_F[NCases][2]);
			}
			// Create array for replicates of 'AllTraits_NCases__selector_rep_F_marginal'
			Discrete[] AllTraits_NCases__selector_rep_F_marginal = new Discrete[this.NumberOfCases];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				AllTraits_NCases__selector_rep_F_marginal[NCases] = ReplicateOp_Divide.MarginalInit<Discrete>(AllTraits_NCases__selector_uses_F[NCases][2]);
			}
			// Create array for replicates of 'AllTraits_NCases__selector_rep_F'
			Discrete[][] AllTraits_NCases__selector_rep_F = new Discrete[this.NumberOfCases][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_rep' Forwards messages.
				AllTraits_NCases__selector_rep_F[NCases] = new Discrete[13];
				for(int Traits = 0; Traits<13; Traits++) {
					AllTraits_NCases__selector_rep_F[NCases][Traits] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(13));
				}
			}
			// Create array for replicates of 'AllTraits_NCases__selector_rep_rep_B_toDef'
			Discrete[][] AllTraits_NCases__selector_rep_rep_B_toDef = new Discrete[this.NumberOfCases][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllTraits_NCases__selector_rep_rep_B_toDef'
				AllTraits_NCases__selector_rep_rep_B_toDef[NCases] = new Discrete[13];
				for(int Traits = 0; Traits<13; Traits++) {
					AllTraits_NCases__selector_rep_rep_B_toDef[NCases][Traits] = ReplicateOp_Divide.ToDefInit<Discrete>(AllTraits_NCases__selector_rep_F[NCases][Traits]);
				}
			}
			// Create array for replicates of 'AllTraits_NCases__selector_rep_rep_F_marginal'
			Discrete[][] AllTraits_NCases__selector_rep_rep_F_marginal = new Discrete[this.NumberOfCases][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllTraits_NCases__selector_rep_rep_F_marginal'
				AllTraits_NCases__selector_rep_rep_F_marginal[NCases] = new Discrete[13];
				for(int Traits = 0; Traits<13; Traits++) {
					AllTraits_NCases__selector_rep_rep_F_marginal[NCases][Traits] = ReplicateOp_Divide.MarginalInit<Discrete>(AllTraits_NCases__selector_rep_F[NCases][Traits]);
				}
			}
			// Create array for replicates of 'AllTraits_NCases__selector_rep_rep_F'
			Discrete[][][] AllTraits_NCases__selector_rep_rep_F = new Discrete[this.NumberOfCases][][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllTraits_NCases__selector_rep_rep_F'
				AllTraits_NCases__selector_rep_rep_F[NCases] = new Discrete[13][];
				for(int Traits = 0; Traits<13; Traits++) {
					// Create array for 'AllTraits_NCases__selector_rep_rep' Forwards messages.
					AllTraits_NCases__selector_rep_rep_F[NCases][Traits] = new Discrete[40];
					for(int Events = 0; Events<40; Events++) {
						AllTraits_NCases__selector_rep_rep_F[NCases][Traits][Events] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(13));
					}
				}
			}
			Discrete AllEvents_NCases__Traits_selector_rep_B_reduced = default(Discrete);
			if (this.NumberOfCases>0) {
				AllEvents_NCases__Traits_selector_rep_B_reduced = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(40));
			}
			// Create array for replicates of 'AllEvents_NCases__Traits_selector_rep_B_toDef'
			Discrete[][] AllEvents_NCases__Traits_selector_rep_B_toDef = new Discrete[this.NumberOfCases][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllEvents_NCases__Traits_selector_rep_B_toDef'
				AllEvents_NCases__Traits_selector_rep_B_toDef[NCases] = new Discrete[13];
				for(int Traits = 0; Traits<13; Traits++) {
					AllEvents_NCases__Traits_selector_rep_B_toDef[NCases][Traits] = ReplicateOp_Divide.ToDefInit<Discrete>(AllEvents_NCases__Traits_selector_uses_F[NCases][Traits][1]);
				}
			}
			// Create array for replicates of 'AllEvents_NCases__Traits_selector_rep_F_marginal'
			Discrete[][] AllEvents_NCases__Traits_selector_rep_F_marginal = new Discrete[this.NumberOfCases][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllEvents_NCases__Traits_selector_rep_F_marginal'
				AllEvents_NCases__Traits_selector_rep_F_marginal[NCases] = new Discrete[13];
				for(int Traits = 0; Traits<13; Traits++) {
					AllEvents_NCases__Traits_selector_rep_F_marginal[NCases][Traits] = ReplicateOp_Divide.MarginalInit<Discrete>(AllEvents_NCases__Traits_selector_uses_F[NCases][Traits][1]);
				}
			}
			// Create array for replicates of 'AllEvents_NCases__Traits_selector_rep_F'
			Discrete[][][] AllEvents_NCases__Traits_selector_rep_F = new Discrete[this.NumberOfCases][][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllEvents_NCases__Traits_selector_rep_F'
				AllEvents_NCases__Traits_selector_rep_F[NCases] = new Discrete[13][];
				for(int Traits = 0; Traits<13; Traits++) {
					// Create array for 'AllEvents_NCases__Traits_selector_rep' Forwards messages.
					AllEvents_NCases__Traits_selector_rep_F[NCases][Traits] = new Discrete[40];
					for(int Events = 0; Events<40; Events++) {
						AllEvents_NCases__Traits_selector_rep_F[NCases][Traits][Events] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(40));
					}
				}
			}
			// Create array for replicates of 'DialogueCPT_Events_Traits_AllRels_NCases___B'
			Dirichlet[][][] DialogueCPT_Events_Traits_AllRels_NCases___B = new Dirichlet[this.NumberOfCases][][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'DialogueCPT_Events_Traits_AllRels_NCases___B'
				DialogueCPT_Events_Traits_AllRels_NCases___B[NCases] = new Dirichlet[13][];
				for(int Traits = 0; Traits<13; Traits++) {
					// Create array for replicates of 'DialogueCPT_Events_Traits_AllRels_NCases___B'
					DialogueCPT_Events_Traits_AllRels_NCases___B[NCases][Traits] = new Dirichlet[40];
					for(int Events = 0; Events<40; Events++) {
						DialogueCPT_Events_Traits_AllRels_NCases___B[NCases][Traits][Events] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][this.AllRels[NCases]]);
						// Message to 'DialogueCPT_Events_Traits_AllRels_NCases__' from Discrete factor
						DialogueCPT_Events_Traits_AllRels_NCases___B[NCases][Traits][Events] = DiscreteFromDirichletOp.ProbsAverageConditional(this.vint__6[NCases], DialogueCPT_Events_Traits_AllRels_NCases___B[NCases][Traits][Events]);
					}
				}
			}
			// Create array for replicates of 'DialogueCPT_Traits_AllRels_NCases___B'
			DistributionRefArray<Dirichlet,Vector>[][] DialogueCPT_Traits_AllRels_NCases___B = new DistributionRefArray<Dirichlet,Vector>[this.NumberOfCases][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'DialogueCPT_Traits_AllRels_NCases___B'
				DialogueCPT_Traits_AllRels_NCases___B[NCases] = new DistributionRefArray<Dirichlet,Vector>[13];
				for(int Traits = 0; Traits<13; Traits++) {
					// Create array for 'DialogueCPT_Traits_AllRels_NCases__' Backwards messages.
					DialogueCPT_Traits_AllRels_NCases___B[NCases][Traits] = new DistributionRefArray<Dirichlet,Vector>(40);
					for(int Events = 0; Events<40; Events++) {
						DialogueCPT_Traits_AllRels_NCases___B[NCases][Traits][Events] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][this.AllRels[NCases]]);
					}
				}
			}
			// Create array for replicates of 'AllTraits_NCases__selector_cases_B'
			DistributionStructArray<Bernoulli,bool>[] AllTraits_NCases__selector_cases_B = new DistributionStructArray<Bernoulli,bool>[this.NumberOfCases];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for 'AllTraits_NCases__selector_cases' Backwards messages.
				AllTraits_NCases__selector_cases_B[NCases] = new DistributionStructArray<Bernoulli,bool>(13);
				for(int Traits = 0; Traits<13; Traits++) {
					AllTraits_NCases__selector_cases_B[NCases][Traits] = Bernoulli.Uniform();
				}
			}
			DistributionRefArray<Discrete,int> AllTraits_F;
			// Create array for 'AllTraits' Forwards messages.
			AllTraits_F = new DistributionRefArray<Discrete,int>(this.NumberOfCases);
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				AllTraits_F[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(13));
			}
			// Create array for replicates of 'AllTraits_NCases__selector_uses_B_toDef'
			Discrete[] AllTraits_NCases__selector_uses_B_toDef = new Discrete[this.NumberOfCases];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				AllTraits_NCases__selector_uses_B_toDef[NCases] = ReplicateOp_Divide.ToDefInit<Discrete>(AllTraits_F[NCases]);
			}
			Dirichlet[] PossibleTraits_rep_B;
			// Create array for 'PossibleTraits_rep' Backwards messages.
			PossibleTraits_rep_B = new Dirichlet[this.NumberOfCases];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				PossibleTraits_rep_B[NCases] = ArrayHelper.MakeUniform<Dirichlet>(this.TraitsPriors);
			}
			Dirichlet PossibleTraits_rep_B_toDef;
			PossibleTraits_rep_B_toDef = ReplicateOp_Divide.ToDefInit<Dirichlet>(this.TraitsPriors);
			Dirichlet PossibleTraits_rep_F_marginal;
			PossibleTraits_rep_F_marginal = ReplicateOp_Divide.MarginalInit<Dirichlet>(this.TraitsPriors);
			// Create array for replicates of 'AllTraits_NCases__selector_uses_F_marginal'
			Discrete[] AllTraits_NCases__selector_uses_F_marginal = new Discrete[this.NumberOfCases];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				AllTraits_NCases__selector_uses_F_marginal[NCases] = ReplicateOp_Divide.MarginalInit<Discrete>(AllTraits_F[NCases]);
			}
			// Create array for replicates of 'AllEvents_NCases__Traits_selector_B'
			Discrete[][] AllEvents_NCases__Traits_selector_B = new Discrete[this.NumberOfCases][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllEvents_NCases__Traits_selector_B'
				AllEvents_NCases__Traits_selector_B[NCases] = new Discrete[13];
				for(int Traits = 0; Traits<13; Traits++) {
					AllEvents_NCases__Traits_selector_B[NCases][Traits] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(40));
				}
			}
			DistributionRefArray<Discrete,int> AllEvents_use_B;
			// Create array for 'AllEvents_use' Backwards messages.
			AllEvents_use_B = new DistributionRefArray<Discrete,int>(this.NumberOfCases);
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				AllEvents_use_B[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(40));
			}
			for(int iteration = this.numberOfIterationsDone; iteration<numberOfIterations; iteration++) {
				for(int Traits = 0; Traits<13; Traits++) {
					for(int Events = 0; Events<40; Events++) {
						this.DialogueCPT_use_F_Events__Traits__marginal[Traits][Events] = GetItemsOp<Vector>.Marginal<DistributionRefArray<Dirichlet,Vector>,Dirichlet>(this.DialogueCPTPrior[Events][Traits], this.DialogueCPT_use_B[Events][Traits], this.DialogueCPT_use_F_Events__Traits__marginal[Traits][Events]);
					}
				}
				for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
					for(int Traits = 0; Traits<13; Traits++) {
						for(int Events = 0; Events<40; Events++) {
							// Message to 'DialogueCPT_itemAllRels_NCases_' from GetItems factor
							this.DialogueCPT_itemAllRels_NCases__F[Traits][Events][NCases] = GetItemsOp<Vector>.ItemsAverageConditional<DistributionRefArray<Dirichlet,Vector>,Dirichlet>(this.DialogueCPT_itemAllRels_NCases__B[Traits][Events][NCases], this.DialogueCPT_F[Events][Traits], this.DialogueCPT_use_F_Events__Traits__marginal[Traits][Events], this.AllRels, NCases, this.DialogueCPT_itemAllRels_NCases__F[Traits][Events][NCases]);
						}
					}
				}
				PossibleEvents_rep_F_marginal = ReplicateOp_Divide.Marginal<Dirichlet>(this.PossibleEvents_rep_B_toDef, this.EventsPriors, PossibleEvents_rep_F_marginal);
				for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
					// Message to 'PossibleEvents_rep' from Replicate factor
					PossibleEvents_rep_F[NCases] = ReplicateOp_Divide.UsesAverageConditional<Dirichlet>(this.PossibleEvents_rep_B[NCases], PossibleEvents_rep_F_marginal, NCases, PossibleEvents_rep_F[NCases]);
					// Message to 'AllEvents' from Discrete factor
					AllEvents_F[NCases] = DiscreteFromDirichletOp.SampleAverageConditional(PossibleEvents_rep_F[NCases], AllEvents_F[NCases]);
					for(int Traits = 0; Traits<13; Traits++) {
						// Message to 'AllEvents_NCases__Traits_selector_uses' from Replicate factor
						AllEvents_NCases__Traits_selector_uses_F[NCases][Traits][0] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(AllEvents_NCases__Traits_selector_uses_B[NCases][Traits], AllEvents_F[NCases], 0, AllEvents_NCases__Traits_selector_uses_F[NCases][Traits][0]);
						// Message to 'AllTraits_NCases__selector_cases_uses' from CasesInt factor
						AllTraits_NCases__selector_cases_uses_B[NCases][Traits][6] = Bernoulli.FromLogOdds(IntCasesOp.LogEvidenceRatio(this.AllEvents_NCases__Traits_selector_cases_B[NCases][Traits], AllEvents_NCases__Traits_selector_uses_F[NCases][Traits][0]));
						for(int Events = 0; Events<40; Events++) {
							// Message to 'AllEvents_NCases__Traits_selector_cases_uses' from Discrete factor
							this.AllEvents_NCases__Traits_selector_cases_uses_B[NCases][Traits][Events][2] = Bernoulli.FromLogOdds(DiscreteFromDirichletOp.LogEvidenceRatio(this.vint__6[NCases], this.DialogueCPT_itemAllRels_NCases__F[Traits][Events][NCases]));
							// Message to 'AllEvents_NCases__Traits_selector_cases' from Replicate factor
							this.AllEvents_NCases__Traits_selector_cases_B[NCases][Traits][Events] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.AllEvents_NCases__Traits_selector_cases_uses_B[NCases][Traits][Events], this.AllEvents_NCases__Traits_selector_cases_B[NCases][Traits][Events]);
						}
						// Message to 'AllEvents_NCases__Traits_selector_uses' from CasesInt factor
						AllEvents_NCases__Traits_selector_uses_B[NCases][Traits][0] = IntCasesOp.IAverageConditional(this.AllEvents_NCases__Traits_selector_cases_B[NCases][Traits], AllEvents_NCases__Traits_selector_uses_B[NCases][Traits][0]);
						// Message to 'AllEvents_NCases__Traits_selector' from Replicate factor
						AllEvents_NCases__Traits_selector_B[NCases][Traits] = ReplicateOp_NoDivide.DefAverageConditional<Discrete>(AllEvents_NCases__Traits_selector_uses_B[NCases][Traits], AllEvents_NCases__Traits_selector_B[NCases][Traits]);
						// Message to 'AllEvents_NCases__Traits_selector_uses' from Replicate factor
						AllEvents_NCases__Traits_selector_uses_F[NCases][Traits][1] = ReplicateOp_NoDivide.UsesAverageConditional<Discrete>(AllEvents_NCases__Traits_selector_uses_B[NCases][Traits], AllEvents_F[NCases], 1, AllEvents_NCases__Traits_selector_uses_F[NCases][Traits][1]);
						// Message to 'AllTraits_NCases__selector_cases_uses' from Replicate factor
						AllTraits_NCases__selector_cases_uses_B[NCases][Traits][5] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Discrete>(AllEvents_NCases__Traits_selector_uses_B[NCases][Traits], AllEvents_F[NCases], AllEvents_NCases__Traits_selector_uses_F[NCases][Traits]));
						// Message to 'AllTraits_NCases__selector_cases' from Replicate factor
						AllTraits_NCases__selector_cases_B[NCases][Traits] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(AllTraits_NCases__selector_cases_uses_B[NCases][Traits], AllTraits_NCases__selector_cases_B[NCases][Traits]);
					}
					// Message to 'AllTraits_NCases__selector_uses' from CasesInt factor
					AllTraits_NCases__selector_uses_B[NCases][0] = IntCasesOp.IAverageConditional(AllTraits_NCases__selector_cases_B[NCases], AllTraits_NCases__selector_uses_B[NCases][0]);
					AllTraits_NCases__selector_uses_B_toDef[NCases] = ReplicateOp_Divide.ToDef<Discrete>(AllTraits_NCases__selector_uses_B[NCases], AllTraits_NCases__selector_uses_B_toDef[NCases]);
					// Message to 'PossibleTraits_rep' from Discrete factor
					PossibleTraits_rep_B[NCases] = DiscreteFromDirichletOp.ProbsAverageConditional(AllTraits_NCases__selector_uses_B_toDef[NCases], this.PossibleTraits_rep_F[NCases], PossibleTraits_rep_B[NCases]);
				}
				PossibleTraits_rep_B_toDef = ReplicateOp_Divide.ToDef<Dirichlet>(PossibleTraits_rep_B, PossibleTraits_rep_B_toDef);
				PossibleTraits_rep_F_marginal = ReplicateOp_Divide.Marginal<Dirichlet>(PossibleTraits_rep_B_toDef, this.TraitsPriors, PossibleTraits_rep_F_marginal);
				for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
					// Message to 'PossibleTraits_rep' from Replicate factor
					this.PossibleTraits_rep_F[NCases] = ReplicateOp_Divide.UsesAverageConditional<Dirichlet>(PossibleTraits_rep_B[NCases], PossibleTraits_rep_F_marginal, NCases, this.PossibleTraits_rep_F[NCases]);
					// Message to 'AllTraits' from Discrete factor
					AllTraits_F[NCases] = DiscreteFromDirichletOp.SampleAverageConditional(this.PossibleTraits_rep_F[NCases], AllTraits_F[NCases]);
					AllTraits_NCases__selector_uses_F_marginal[NCases] = ReplicateOp_Divide.Marginal<Discrete>(AllTraits_NCases__selector_uses_B_toDef[NCases], AllTraits_F[NCases], AllTraits_NCases__selector_uses_F_marginal[NCases]);
					// Message to 'AllTraits_NCases__selector_uses' from Replicate factor
					AllTraits_NCases__selector_uses_F[NCases][1] = ReplicateOp_Divide.UsesAverageConditional<Discrete>(AllTraits_NCases__selector_uses_B[NCases][1], AllTraits_NCases__selector_uses_F_marginal[NCases], 1, AllTraits_NCases__selector_uses_F[NCases][1]);
					// Message to 'AllEvents_use' from Enter factor
					AllEvents_use_B[NCases] = BeliefPropagationGateEnterOp.ValueAverageConditional<Discrete>(AllEvents_NCases__Traits_selector_B[NCases], AllTraits_NCases__selector_uses_F[NCases][1], AllEvents_F[NCases], AllEvents_use_B[NCases]);
					// Message to 'AllTraits_NCases__selector_uses' from Replicate factor
					AllTraits_NCases__selector_uses_F[NCases][2] = ReplicateOp_Divide.UsesAverageConditional<Discrete>(AllTraits_NCases__selector_rep_B_toDef[NCases], AllTraits_NCases__selector_uses_F_marginal[NCases], 2, AllTraits_NCases__selector_uses_F[NCases][2]);
					AllTraits_NCases__selector_rep_F_marginal[NCases] = ReplicateOp_Divide.Marginal<Discrete>(AllTraits_NCases__selector_rep_B_toDef[NCases], AllTraits_NCases__selector_uses_F[NCases][2], AllTraits_NCases__selector_rep_F_marginal[NCases]);
					for(int Traits = 0; Traits<13; Traits++) {
						AllEvents_NCases__Traits_selector_rep_F_marginal[NCases][Traits] = ReplicateOp_Divide.Marginal<Discrete>(AllEvents_NCases__Traits_selector_rep_B_toDef[NCases][Traits], AllEvents_NCases__Traits_selector_uses_F[NCases][Traits][1], AllEvents_NCases__Traits_selector_rep_F_marginal[NCases][Traits]);
						// Message to 'AllTraits_NCases__selector_rep' from Replicate factor
						AllTraits_NCases__selector_rep_F[NCases][Traits] = ReplicateOp_Divide.UsesAverageConditional<Discrete>(AllTraits_NCases__selector_rep_rep_B_toDef[NCases][Traits], AllTraits_NCases__selector_rep_F_marginal[NCases], Traits, AllTraits_NCases__selector_rep_F[NCases][Traits]);
						AllTraits_NCases__selector_rep_rep_F_marginal[NCases][Traits] = ReplicateOp_Divide.Marginal<Discrete>(AllTraits_NCases__selector_rep_rep_B_toDef[NCases][Traits], AllTraits_NCases__selector_rep_F[NCases][Traits], AllTraits_NCases__selector_rep_rep_F_marginal[NCases][Traits]);
						for(int Events = 0; Events<40; Events++) {
							// Message to 'AllEvents_NCases__Traits_selector_rep' from Replicate factor
							AllEvents_NCases__Traits_selector_rep_F[NCases][Traits][Events] = ReplicateOp_Divide.UsesAverageConditional<Discrete>(AllEvents_NCases__Traits_selector_rep_B_reduced, AllEvents_NCases__Traits_selector_rep_F_marginal[NCases][Traits], Events, AllEvents_NCases__Traits_selector_rep_F[NCases][Traits][Events]);
							// Message to 'DialogueCPT_Traits_AllRels_NCases__' from EnterOne factor
							DialogueCPT_Traits_AllRels_NCases___B[NCases][Traits][Events] = GateEnterOneOp<Vector>.ValueAverageConditional<Dirichlet>(DialogueCPT_Events_Traits_AllRels_NCases___B[NCases][Traits][Events], AllEvents_NCases__Traits_selector_rep_F[NCases][Traits][Events], this.DialogueCPT_itemAllRels_NCases__F[Traits][Events][NCases], Events, DialogueCPT_Traits_AllRels_NCases___B[NCases][Traits][Events]);
							// Message to 'AllTraits_NCases__selector_rep_rep' from Replicate factor
							AllTraits_NCases__selector_rep_rep_F[NCases][Traits][Events] = ReplicateOp_Divide.UsesAverageConditional<Discrete>(AllTraits_NCases__selector_rep_rep_B_reduced, AllTraits_NCases__selector_rep_rep_F_marginal[NCases][Traits], Events, AllTraits_NCases__selector_rep_rep_F[NCases][Traits][Events]);
							// Message to 'DialogueCPT_itemAllRels_NCases_' from EnterOne factor
							this.DialogueCPT_itemAllRels_NCases__B[Traits][Events][NCases] = GateEnterOneOp<Vector>.ValueAverageConditional<Dirichlet>(DialogueCPT_Traits_AllRels_NCases___B[NCases][Traits][Events], AllTraits_NCases__selector_rep_rep_F[NCases][Traits][Events], this.DialogueCPT_itemAllRels_NCases__F[Traits][Events][NCases], Traits, this.DialogueCPT_itemAllRels_NCases__B[Traits][Events][NCases]);
						}
					}
					// Message to 'PossibleEvents_rep' from Discrete factor
					this.PossibleEvents_rep_B[NCases] = DiscreteFromDirichletOp.ProbsAverageConditional(AllEvents_use_B[NCases], PossibleEvents_rep_F[NCases], this.PossibleEvents_rep_B[NCases]);
				}
				this.PossibleEvents_rep_B_toDef = ReplicateOp_Divide.ToDef<Dirichlet>(this.PossibleEvents_rep_B, this.PossibleEvents_rep_B_toDef);
				for(int Traits = 0; Traits<13; Traits++) {
					for(int Events = 0; Events<40; Events++) {
						// Message to 'DialogueCPT_use' from GetItems factor
						this.DialogueCPT_use_B[Events][Traits] = GetItemsOp<Vector>.ArrayAverageConditional<Dirichlet,DistributionRefArray<Dirichlet,Vector>>(this.DialogueCPT_itemAllRels_NCases__B[Traits][Events], this.AllRels, this.DialogueCPT_use_B[Events][Traits]);
					}
				}
				this.OnProgressChanged(new ProgressChangedEventArgs(iteration));
			}
			// Message to 'PossibleEvents_marginal' from Variable factor
			this.PossibleEvents_marginal_F = VariableOp.MarginalAverageConditional<Dirichlet>(this.PossibleEvents_rep_B_toDef, this.EventsPriors, this.PossibleEvents_marginal_F);
			this.PossibleTraits_marginal_F = ArrayHelper.MakeUniform<Dirichlet>(this.TraitsPriors);
			// Message to 'PossibleTraits_marginal' from Variable factor
			this.PossibleTraits_marginal_F = VariableOp.MarginalAverageConditional<Dirichlet>(PossibleTraits_rep_B_toDef, this.TraitsPriors, this.PossibleTraits_marginal_F);
			// Create array for 'DialogueCPT_marginal' Forwards messages.
			this.DialogueCPT_marginal_F = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(40);
			for(int Events = 0; Events<40; Events++) {
				// Create array for 'DialogueCPT_marginal' Forwards messages.
				this.DialogueCPT_marginal_F[Events] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(13);
			}
			for(int Traits = 0; Traits<13; Traits++) {
				for(int Events = 0; Events<40; Events++) {
					// Create array for 'DialogueCPT_marginal' Forwards messages.
					this.DialogueCPT_marginal_F[Events][Traits] = new DistributionRefArray<Dirichlet,Vector>(4);
					for(int Rel = 0; Rel<4; Rel++) {
						this.DialogueCPT_marginal_F[Events][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][Rel]);
						// Message to 'DialogueCPT_marginal' from Variable factor
						this.DialogueCPT_marginal_F[Events][Traits][Rel] = VariableOp.MarginalAverageConditional<Dirichlet>(this.DialogueCPT_use_B[Events][Traits][Rel], this.DialogueCPTPrior[Events][Traits][Rel], this.DialogueCPT_marginal_F[Events][Traits][Rel]);
					}
				}
			}
			// Create array for 'AllEvents_marginal' Forwards messages.
			this.AllEvents_marginal_F = new DistributionRefArray<Discrete,int>(this.NumberOfCases);
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				this.AllEvents_marginal_F[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(40));
				// Message to 'AllEvents_marginal' from Variable factor
				this.AllEvents_marginal_F[NCases] = VariableOp.MarginalAverageConditional<Discrete>(AllEvents_use_B[NCases], AllEvents_F[NCases], this.AllEvents_marginal_F[NCases]);
			}
			// Create array for 'AllTraits_marginal' Forwards messages.
			this.AllTraits_marginal_F = new DistributionRefArray<Discrete,int>(this.NumberOfCases);
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				this.AllTraits_marginal_F[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(13));
				// Message to 'AllTraits_marginal' from Variable factor
				this.AllTraits_marginal_F[NCases] = VariableOp.MarginalAverageConditional<Discrete>(AllTraits_NCases__selector_uses_B_toDef[NCases], AllTraits_F[NCases], this.AllTraits_marginal_F[NCases]);
			}
			this.Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of AllRels and DialogueCPTPrior and NumberOfCases and numberOfIterationsDecreased and must reset on changes to EventsPriors and TraitsPriors and vint__6</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4(bool initialise)
		{
			if (this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isDone&&((!initialise)||this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isInitialised)) {
				return ;
			}
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				for(int Traits = 0; Traits<13; Traits++) {
					for(int Events = 0; Events<40; Events++) {
						this.DialogueCPT_itemAllRels_NCases__B[Traits][Events][NCases] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][this.AllRels[NCases]]);
						this.DialogueCPT_itemAllRels_NCases__F[Traits][Events][NCases] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][this.AllRels[NCases]]);
						// Message to 'DialogueCPT_itemAllRels_NCases_' from GetItems factor
						this.DialogueCPT_itemAllRels_NCases__F[Traits][Events][NCases] = GetItemsOp<Vector>.ItemsAverageConditional<DistributionRefArray<Dirichlet,Vector>,Dirichlet>(this.DialogueCPT_itemAllRels_NCases__B[Traits][Events][NCases], this.DialogueCPT_F[Events][Traits], this.DialogueCPT_use_F_Events__Traits__marginal[Traits][Events], this.AllRels, NCases, this.DialogueCPT_itemAllRels_NCases__F[Traits][Events][NCases]);
					}
				}
			}
			this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isDone = true;
			this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of AllRels and DialogueCPTPrior and NumberOfCases and numberOfIterationsDecreased and vint__6 and must reset on changes to EventsPriors and TraitsPriors</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10(bool initialise)
		{
			if (this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isDone&&((!initialise)||this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isInitialised)) {
				return ;
			}
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				for(int Traits = 0; Traits<13; Traits++) {
					for(int Events = 0; Events<40; Events++) {
						// Message to 'AllEvents_NCases__Traits_selector_cases_uses' from Discrete factor
						this.AllEvents_NCases__Traits_selector_cases_uses_B[NCases][Traits][Events][2] = Bernoulli.FromLogOdds(DiscreteFromDirichletOp.LogEvidenceRatio(this.vint__6[NCases], this.DialogueCPT_itemAllRels_NCases__F[Traits][Events][NCases]));
						// Message to 'AllEvents_NCases__Traits_selector_cases' from Replicate factor
						this.AllEvents_NCases__Traits_selector_cases_B[NCases][Traits][Events] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(this.AllEvents_NCases__Traits_selector_cases_uses_B[NCases][Traits][Events], this.AllEvents_NCases__Traits_selector_cases_B[NCases][Traits][Events]);
					}
				}
			}
			this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isDone = true;
			this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of AllRels and NumberOfCases</summary>
		private void Changed_AllRels_NumberOfCases()
		{
			if (this.Changed_AllRels_NumberOfCases_isDone) {
				return ;
			}
			// Create array for 'AllRels_marginal' Forwards messages.
			this.AllRels_marginal_F = new DistributionRefArray<Discrete,int>(this.NumberOfCases);
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				this.AllRels_marginal_F[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(4));
			}
			// Message to 'AllRels_marginal' from DerivedVariable factor
			this.AllRels_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionRefArray<Discrete,int>,int[]>(this.AllRels, this.AllRels_marginal_F);
			this.Changed_AllRels_NumberOfCases_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of AllRels and NumberOfCases and RelStatusPriors</summary>
		private void Changed_AllRels_NumberOfCases_RelStatusPriors()
		{
			if (this.Changed_AllRels_NumberOfCases_RelStatusPriors_isDone) {
				return ;
			}
			this.PossibleRel_marginal_F = ArrayHelper.MakeUniform<Dirichlet>(this.RelStatusPriors);
			Dirichlet[] PossibleRel_rep_B;
			// Create array for 'PossibleRel_rep' Backwards messages.
			PossibleRel_rep_B = new Dirichlet[this.NumberOfCases];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				PossibleRel_rep_B[NCases] = ArrayHelper.MakeUniform<Dirichlet>(this.RelStatusPriors);
				// Message to 'PossibleRel_rep' from Discrete factor
				PossibleRel_rep_B[NCases] = DiscreteFromDirichletOp.ProbsAverageConditional(this.AllRels[NCases], PossibleRel_rep_B[NCases]);
			}
			Dirichlet PossibleRel_rep_B_toDef;
			PossibleRel_rep_B_toDef = ReplicateOp_Divide.ToDefInit<Dirichlet>(this.RelStatusPriors);
			PossibleRel_rep_B_toDef = ReplicateOp_Divide.ToDef<Dirichlet>(PossibleRel_rep_B, PossibleRel_rep_B_toDef);
			// Message to 'PossibleRel_marginal' from Variable factor
			this.PossibleRel_marginal_F = VariableOp.MarginalAverageConditional<Dirichlet>(PossibleRel_rep_B_toDef, this.RelStatusPriors, this.PossibleRel_marginal_F);
			this.Changed_AllRels_NumberOfCases_RelStatusPriors_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of DialogueCPTPrior</summary>
		private void Changed_DialogueCPTPrior()
		{
			if (this.Changed_DialogueCPTPrior_isDone) {
				return ;
			}
			for(int Traits = 0; Traits<13; Traits++) {
				for(int Events = 0; Events<40; Events++) {
					for(int Rel = 0; Rel<4; Rel++) {
						this.DialogueCPT_F[Events][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][Rel]);
					}
				}
			}
			// Create array for 'DialogueCPTPrior_marginal' Forwards messages.
			this.DialogueCPTPrior_marginal_F = new PointMass<Dirichlet[][][]>(this.DialogueCPTPrior);
			// Message to 'DialogueCPTPrior_marginal' from DerivedVariable factor
			this.DialogueCPTPrior_marginal_F = DerivedVariableOp.MarginalAverageConditional<PointMass<Dirichlet[][][]>,Dirichlet[][][]>(this.DialogueCPTPrior, this.DialogueCPTPrior_marginal_F);
			this.Changed_DialogueCPTPrior_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of DialogueCPTPrior and numberOfIterationsDecreased and must reset on changes to AllRels and EventsPriors and NumberOfCases and TraitsPriors and vint__6</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5(bool initialise)
		{
			if (this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isDone&&((!initialise)||this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isInitialised)) {
				return ;
			}
			for(int Traits = 0; Traits<13; Traits++) {
				for(int Events = 0; Events<40; Events++) {
					for(int Rel = 0; Rel<4; Rel++) {
						this.DialogueCPT_use_B[Events][Traits][Rel] = ArrayHelper.MakeUniform<Dirichlet>(this.DialogueCPTPrior[Events][Traits][Rel]);
					}
					this.DialogueCPT_use_F_Events__Traits__marginal[Traits][Events] = GetItemsOp<Vector>.MarginalInit<DistributionRefArray<Dirichlet,Vector>>(this.DialogueCPT_F[Events][Traits]);
					this.DialogueCPT_use_F_Events__Traits__marginal[Traits][Events] = GetItemsOp<Vector>.Marginal<DistributionRefArray<Dirichlet,Vector>,Dirichlet>(this.DialogueCPTPrior[Events][Traits], this.DialogueCPT_use_B[Events][Traits], this.DialogueCPT_use_F_Events__Traits__marginal[Traits][Events]);
				}
			}
			this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isDone = true;
			this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of EventsPriors</summary>
		private void Changed_EventsPriors()
		{
			if (this.Changed_EventsPriors_isDone) {
				return ;
			}
			this.EventsPriors_marginal_F = new PointMass<Dirichlet>(this.EventsPriors);
			// Message to 'EventsPriors_marginal' from DerivedVariable factor
			this.EventsPriors_marginal_F = DerivedVariableOp.MarginalAverageConditional<PointMass<Dirichlet>,Dirichlet>(this.EventsPriors, this.EventsPriors_marginal_F);
			this.Changed_EventsPriors_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of EventsPriors and NumberOfCases and numberOfIterationsDecreased and must reset on changes to AllRels and DialogueCPTPrior and TraitsPriors and vint__6</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8(bool initialise)
		{
			if (this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isDone&&((!initialise)||this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isInitialised)) {
				return ;
			}
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				this.PossibleEvents_rep_B[NCases] = ArrayHelper.MakeUniform<Dirichlet>(this.EventsPriors);
			}
			this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isDone = true;
			this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of EventsPriors and numberOfIterationsDecreased and must reset on changes to AllRels and DialogueCPTPrior and NumberOfCases and TraitsPriors and vint__6</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9(bool initialise)
		{
			if (this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isDone&&((!initialise)||this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isInitialised)) {
				return ;
			}
			this.PossibleEvents_rep_B_toDef = ReplicateOp_Divide.ToDefInit<Dirichlet>(this.EventsPriors);
			this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isDone = true;
			this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of NumberOfCases</summary>
		private void Changed_NumberOfCases()
		{
			if (this.Changed_NumberOfCases_isDone) {
				return ;
			}
			// Create array for replicates of 'AllEvents_NCases__Traits_selector_cases_uses_B'
			this.AllEvents_NCases__Traits_selector_cases_uses_B = new Bernoulli[this.NumberOfCases][][][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllEvents_NCases__Traits_selector_cases_uses_B'
				this.AllEvents_NCases__Traits_selector_cases_uses_B[NCases] = new Bernoulli[13][][];
				for(int Traits = 0; Traits<13; Traits++) {
					// Create array for 'AllEvents_NCases__Traits_selector_cases_uses' Backwards messages.
					this.AllEvents_NCases__Traits_selector_cases_uses_B[NCases][Traits] = new Bernoulli[40][];
					for(int Events = 0; Events<40; Events++) {
						// Create array for 'AllEvents_NCases__Traits_selector_cases_uses' Backwards messages.
						this.AllEvents_NCases__Traits_selector_cases_uses_B[NCases][Traits][Events] = new Bernoulli[3];
						this.AllEvents_NCases__Traits_selector_cases_uses_B[NCases][Traits][Events][1] = Bernoulli.Uniform();
						this.AllEvents_NCases__Traits_selector_cases_uses_B[NCases][Traits][Events][0] = Bernoulli.Uniform();
					}
				}
			}
			for(int Traits = 0; Traits<13; Traits++) {
				for(int Events = 0; Events<40; Events++) {
					// Create array for 'DialogueCPT_itemAllRels_NCases_' Backwards messages.
					this.DialogueCPT_itemAllRels_NCases__B[Traits][Events] = new DistributionRefArray<Dirichlet,Vector>(this.NumberOfCases);
					// Create array for 'DialogueCPT_itemAllRels_NCases_' Forwards messages.
					this.DialogueCPT_itemAllRels_NCases__F[Traits][Events] = new DistributionRefArray<Dirichlet,Vector>(this.NumberOfCases);
				}
			}
			// Create array for replicates of 'AllEvents_NCases__Traits_selector_cases_B'
			this.AllEvents_NCases__Traits_selector_cases_B = new DistributionStructArray<Bernoulli,bool>[this.NumberOfCases][];
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				// Create array for replicates of 'AllEvents_NCases__Traits_selector_cases_B'
				this.AllEvents_NCases__Traits_selector_cases_B[NCases] = new DistributionStructArray<Bernoulli,bool>[13];
				for(int Traits = 0; Traits<13; Traits++) {
					// Create array for 'AllEvents_NCases__Traits_selector_cases' Backwards messages.
					this.AllEvents_NCases__Traits_selector_cases_B[NCases][Traits] = new DistributionStructArray<Bernoulli,bool>(40);
				}
			}
			// Create array for 'PossibleTraits_rep' Forwards messages.
			this.PossibleTraits_rep_F = new Dirichlet[this.NumberOfCases];
			// Create array for 'PossibleEvents_rep' Backwards messages.
			this.PossibleEvents_rep_B = new Dirichlet[this.NumberOfCases];
			this.NumberOfCases_marginal_F = new PointMass<int>(this.NumberOfCases);
			// Message to 'NumberOfCases_marginal' from DerivedVariable factor
			this.NumberOfCases_marginal_F = DerivedVariableOp.MarginalAverageConditional<PointMass<int>,int>(this.NumberOfCases, this.NumberOfCases_marginal_F);
			this.Changed_NumberOfCases_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of NumberOfCases and numberOfIterationsDecreased and must reset on changes to AllRels and DialogueCPTPrior and EventsPriors and TraitsPriors and vint__6</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2(bool initialise)
		{
			if (this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isDone&&((!initialise)||this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isInitialised)) {
				return ;
			}
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				for(int Traits = 0; Traits<13; Traits++) {
					for(int Events = 0; Events<40; Events++) {
						this.AllEvents_NCases__Traits_selector_cases_uses_B[NCases][Traits][Events][2] = Bernoulli.Uniform();
						this.AllEvents_NCases__Traits_selector_cases_B[NCases][Traits][Events] = Bernoulli.Uniform();
					}
				}
			}
			this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isDone = true;
			this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of NumberOfCases and numberOfIterationsDecreased and TraitsPriors and must reset on changes to AllRels and DialogueCPTPrior and EventsPriors and vint__6</summary>
		/// <param name="initialise">If true, reset messages that initialise loops</param>
		private void Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7(bool initialise)
		{
			if (this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isDone&&((!initialise)||this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isInitialised)) {
				return ;
			}
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				this.PossibleTraits_rep_F[NCases] = ArrayHelper.MakeUniform<Dirichlet>(this.TraitsPriors);
			}
			this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isDone = true;
			this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isInitialised = true;
		}

		/// <summary>Computations that depend on the observed value of NumberOfCases and vint__6</summary>
		private void Changed_NumberOfCases_vint__6()
		{
			if (this.Changed_NumberOfCases_vint__6_isDone) {
				return ;
			}
			// Create array for 'vint__6_marginal' Forwards messages.
			this.vint__6_marginal_F = new DistributionRefArray<Discrete,int>(this.NumberOfCases);
			for(int NCases = 0; NCases<this.NumberOfCases; NCases++) {
				this.vint__6_marginal_F[NCases] = ArrayHelper.MakeUniform<Discrete>(Discrete.Uniform(646));
			}
			// Message to 'vint__6_marginal' from DerivedVariable factor
			this.vint__6_marginal_F = DerivedVariableOp.MarginalAverageConditional<DistributionRefArray<Discrete,int>,int[]>(this.vint__6, this.vint__6_marginal_F);
			this.Changed_NumberOfCases_vint__6_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of RelStatusPriors</summary>
		private void Changed_RelStatusPriors()
		{
			if (this.Changed_RelStatusPriors_isDone) {
				return ;
			}
			this.RelStatusPriors_marginal_F = new PointMass<Dirichlet>(this.RelStatusPriors);
			// Message to 'RelStatusPriors_marginal' from DerivedVariable factor
			this.RelStatusPriors_marginal_F = DerivedVariableOp.MarginalAverageConditional<PointMass<Dirichlet>,Dirichlet>(this.RelStatusPriors, this.RelStatusPriors_marginal_F);
			this.Changed_RelStatusPriors_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of TraitsPriors</summary>
		private void Changed_TraitsPriors()
		{
			if (this.Changed_TraitsPriors_isDone) {
				return ;
			}
			this.TraitsPriors_marginal_F = new PointMass<Dirichlet>(this.TraitsPriors);
			// Message to 'TraitsPriors_marginal' from DerivedVariable factor
			this.TraitsPriors_marginal_F = DerivedVariableOp.MarginalAverageConditional<PointMass<Dirichlet>,Dirichlet>(this.TraitsPriors, this.TraitsPriors_marginal_F);
			this.Changed_TraitsPriors_isDone = true;
		}

		/// <summary>Computations that do not depend on observed values</summary>
		private void Constant()
		{
			if (this.Constant_isDone) {
				return ;
			}
			// Create array for replicates of 'DialogueCPT_itemAllRels_NCases__B'
			this.DialogueCPT_itemAllRels_NCases__B = new DistributionRefArray<Dirichlet,Vector>[13][];
			for(int Traits = 0; Traits<13; Traits++) {
				// Create array for replicates of 'DialogueCPT_itemAllRels_NCases__B'
				this.DialogueCPT_itemAllRels_NCases__B[Traits] = new DistributionRefArray<Dirichlet,Vector>[40];
			}
			// Create array for 'DialogueCPT_use' Backwards messages.
			this.DialogueCPT_use_B = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(40);
			for(int Events = 0; Events<40; Events++) {
				// Create array for 'DialogueCPT_use' Backwards messages.
				this.DialogueCPT_use_B[Events] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(13);
			}
			for(int Traits = 0; Traits<13; Traits++) {
				for(int Events = 0; Events<40; Events++) {
					// Create array for 'DialogueCPT_use' Backwards messages.
					this.DialogueCPT_use_B[Events][Traits] = new DistributionRefArray<Dirichlet,Vector>(4);
				}
			}
			// Create array for 'DialogueCPT' Forwards messages.
			this.DialogueCPT_F = new DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]>(40);
			for(int Events = 0; Events<40; Events++) {
				// Create array for 'DialogueCPT' Forwards messages.
				this.DialogueCPT_F[Events] = new DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>(13);
			}
			for(int Traits = 0; Traits<13; Traits++) {
				for(int Events = 0; Events<40; Events++) {
					// Create array for 'DialogueCPT' Forwards messages.
					this.DialogueCPT_F[Events][Traits] = new DistributionRefArray<Dirichlet,Vector>(4);
				}
			}
			// Create array for replicates of 'DialogueCPT_use_F_Events__Traits__marginal'
			this.DialogueCPT_use_F_Events__Traits__marginal = new DistributionRefArray<Dirichlet,Vector>[13][];
			for(int Traits = 0; Traits<13; Traits++) {
				// Create array for replicates of 'DialogueCPT_use_F_Events__Traits__marginal'
				this.DialogueCPT_use_F_Events__Traits__marginal[Traits] = new DistributionRefArray<Dirichlet,Vector>[40];
			}
			// Create array for replicates of 'DialogueCPT_itemAllRels_NCases__F'
			this.DialogueCPT_itemAllRels_NCases__F = new DistributionRefArray<Dirichlet,Vector>[13][];
			for(int Traits = 0; Traits<13; Traits++) {
				// Create array for replicates of 'DialogueCPT_itemAllRels_NCases__F'
				this.DialogueCPT_itemAllRels_NCases__F[Traits] = new DistributionRefArray<Dirichlet,Vector>[40];
			}
			this.Constant_isDone = true;
		}

		/// <summary>
		/// Returns the marginal distribution for 'DialogueCPT' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<DistributionRefArray<DistributionRefArray<Dirichlet,Vector>,Vector[]>,Vector[][]> DialogueCPTMarginal()
		{
			return this.DialogueCPT_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'DialogueCPTPrior' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public PointMass<Dirichlet[][][]> DialogueCPTPriorMarginal()
		{
			return this.DialogueCPTPrior_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'EventsPriors' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public PointMass<Dirichlet> EventsPriorsMarginal()
		{
			return this.EventsPriors_marginal_F;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			if (numberOfIterations!=this.numberOfIterationsDone) {
				if (numberOfIterations<this.numberOfIterationsDone) {
					this.numberOfIterationsDone = 0;
					this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9_isDone = false;
					this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5_isDone = false;
					this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8_isDone = false;
					this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7_isDone = false;
					this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4_isDone = false;
					this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2_isDone = false;
					this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10_isDone = false;
				}
				this.Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6_isDone = false;
			}
			this.Changed_NumberOfCases_vint__6();
			this.Changed_AllRels_NumberOfCases();
			this.Changed_RelStatusPriors();
			this.Changed_TraitsPriors();
			this.Changed_EventsPriors();
			this.Changed_AllRels_NumberOfCases_RelStatusPriors();
			this.Constant();
			this.Changed_EventsPriors_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_NumberOfCases_TraitsP9(initialise);
			this.Changed_DialogueCPTPrior();
			this.Changed_DialogueCPTPrior_numberOfIterationsDecreased_Init_AllRels_EventsPriors_NumberOfCases_TraitsP5(initialise);
			this.Changed_NumberOfCases();
			this.Changed_EventsPriors_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_TraitsP8(initialise);
			this.Changed_NumberOfCases_numberOfIterationsDecreased_TraitsPriors_Init_AllRels_DialogueCPTPrior_EventsP7(initialise);
			this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_Init_EventsPriors_TraitsP4(initialise);
			this.Changed_NumberOfCases_numberOfIterationsDecreased_Init_AllRels_DialogueCPTPrior_EventsPriors_TraitsP2(initialise);
			this.Changed_AllRels_DialogueCPTPrior_NumberOfCases_numberOfIterationsDecreased_vint__6_Init_EventsPriors10(initialise);
			this.Changed_AllRels_DialogueCPTPrior_EventsPriors_NumberOfCases_numberOfIterations_TraitsPriors_vint__6(numberOfIterations);
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="NumberOfCases") {
				return this.NumberOfCases;
			}
			if (variableName=="EventsPriors") {
				return this.EventsPriors;
			}
			if (variableName=="TraitsPriors") {
				return this.TraitsPriors;
			}
			if (variableName=="RelStatusPriors") {
				return this.RelStatusPriors;
			}
			if (variableName=="DialogueCPTPrior") {
				return this.DialogueCPTPrior;
			}
			if (variableName=="AllRels") {
				return this.AllRels;
			}
			if (variableName=="vint__6") {
				return this.vint__6;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vint__6") {
				return this.Vint__6Marginal();
			}
			if (variableName=="AllRels") {
				return this.AllRelsMarginal();
			}
			if (variableName=="RelStatusPriors") {
				return this.RelStatusPriorsMarginal();
			}
			if (variableName=="TraitsPriors") {
				return this.TraitsPriorsMarginal();
			}
			if (variableName=="EventsPriors") {
				return this.EventsPriorsMarginal();
			}
			if (variableName=="PossibleRel") {
				return this.PossibleRelMarginal();
			}
			if (variableName=="DialogueCPTPrior") {
				return this.DialogueCPTPriorMarginal();
			}
			if (variableName=="NumberOfCases") {
				return this.NumberOfCasesMarginal();
			}
			if (variableName=="PossibleEvents") {
				return this.PossibleEventsMarginal();
			}
			if (variableName=="PossibleTraits") {
				return this.PossibleTraitsMarginal();
			}
			if (variableName=="DialogueCPT") {
				return this.DialogueCPTMarginal();
			}
			if (variableName=="AllEvents") {
				return this.AllEventsMarginal();
			}
			if (variableName=="AllTraits") {
				return this.AllTraitsMarginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		/// <summary>
		/// Returns the marginal distribution for 'NumberOfCases' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public PointMass<int> NumberOfCasesMarginal()
		{
			return this.NumberOfCases_marginal_F;
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>
		/// Returns the marginal distribution for 'PossibleEvents' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Dirichlet PossibleEventsMarginal()
		{
			return this.PossibleEvents_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'PossibleRel' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Dirichlet PossibleRelMarginal()
		{
			return this.PossibleRel_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'PossibleTraits' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Dirichlet PossibleTraitsMarginal()
		{
			return this.PossibleTraits_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'RelStatusPriors' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public PointMass<Dirichlet> RelStatusPriorsMarginal()
		{
			return this.RelStatusPriors_marginal_F;
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="NumberOfCases") {
				this.NumberOfCases = (int)value;
				return ;
			}
			if (variableName=="EventsPriors") {
				this.EventsPriors = (Dirichlet)value;
				return ;
			}
			if (variableName=="TraitsPriors") {
				this.TraitsPriors = (Dirichlet)value;
				return ;
			}
			if (variableName=="RelStatusPriors") {
				this.RelStatusPriors = (Dirichlet)value;
				return ;
			}
			if (variableName=="DialogueCPTPrior") {
				this.DialogueCPTPrior = (Dirichlet[][][])value;
				return ;
			}
			if (variableName=="AllRels") {
				this.AllRels = (int[])value;
				return ;
			}
			if (variableName=="vint__6") {
				this.vint__6 = (int[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>
		/// Returns the marginal distribution for 'TraitsPriors' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public PointMass<Dirichlet> TraitsPriorsMarginal()
		{
			return this.TraitsPriors_marginal_F;
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vint__6' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionRefArray<Discrete,int> Vint__6Marginal()
		{
			return this.vint__6_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
